apiVersion: v1
kind: Secret
metadata:
    name: actual-secrets
    namespace: home
stringData:
    ACTUAL_OPENID_DISCOVERY_URL: ENC[AES256_GCM,data:PTv5VBxEuLBxrCQUElEJ+JW1Ps1JtvABB512n9hzfIZn++LyLEZTYxHZ+Xiwcxj6SyQJtoK2QAw36G+FPPL/Eqb1MnZOGQ08YCED,iv:J/hmQbmCJnfttCbsWjW1UsL4EOLtISQzyY7trS4SXjk=,tag:B6t46jbgr/hlCPe9NeuMvg==,type:str]
    ACTUAL_OPENID_CLIENT_ID: ENC[AES256_GCM,data:bPsmzda0BDgSn5y0C1poWpPDs7/c3m+Iv1yuIGP4TcswPys3Ibgxag==,iv:uASUW34em07C6obTNYIogGoe1P0CtXbEWeVT24FwG5g=,tag:+xh71HHzYTgGKW1mgoPh7g==,type:str]
    ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:MYo/Ac5GVnyPVU5EqKn5VDWk8xGVjmVZFNIgZjxxCUGRns/4uEbmyiu0+gP1NgfdM5USf/TNGOnB6yPKMCgZiIAup4qab0QsmX5KtQq9a7YQ9Lp4HNwfCpS9Bw6FqQhmYNWpawz+8Sv/Jp5hBUk+A32QSrT3f1LROY0esVmwmYc=,iv:E2mwbb739Qt/nNTGPZI3CusJw5jLwA/auUZaaf6ZNew=,tag:DZK2+Fd0g/rBPaWr2u3sPQ==,type:str]
    ACTUAL_OPENID_SERVER_HOSTNAME: ENC[AES256_GCM,data:qqww65lVH5+8Pp4HCnxxx0LxgjTCufU=,iv:JKlICSn2Wk6mr7CsqFgdx2RUJv/8cpQT4qRNhOsoKyM=,tag:kI4UbZ9Xogt7mHCSKENT7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRVYza1ViUkhpMWhVYXlU
            WlJzQlE5dzRtMUZ5RERPNXNERUlvbkxsRG1FCjRQNk5rQjI0U3hlV3FkbzVmQ0lW
            ajE1NCtyTlhGWGJPbTJ2eSt5am0zTWsKLS0tIFk5RXV5SmpoSkZEN2k5eVlRajlC
            TnlIRk93eGNRSmJQUmhKTE9LcFJWa1UKAsm25WJLZB/RsVqgM4jvu3RqgMfhHO0S
            Tp94vmKaZceTBOhoWj8BQj6lQjGuoQymH5kvZJRvABvPemhLkrC1xA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T09:30:35Z"
    mac: ENC[AES256_GCM,data:C+bsqfWmlzr250stmQ2Jl+zQUB9Bv1gF4dkp/d/scTtkUIu7T3KEtGqpDXQznQ0WaKETF6kTNEDv2+3SAlg9JSDmVCyCATkI4nsFkNN+zzKbqPg8G9nao3GyLkzrlIqZCrw6FfoURRVltJfQkzlvlLEv+CIzCD7LZTE4l2/363M=,iv:vzmQTOuaXcbbOazOpNtOTyuHzIco4YXi307nY8ZaIo8=,tag:WTllNr1oKtWMmbF3L8PL3Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
