apiVersion: v1
kind: Secret
metadata:
    name: genrpg-prod-secret
    namespace: web
stringData:
    hello_world: ENC[AES256_GCM,data:zG4=,iv:YCJETHtSO/wAjHqz5ZaMiquvnXwGHva31o7/RTqe80c=,tag:V02AYbGUpir2NcKsF2PhyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb2dDWm4raWc3MHYxVGRm
            dkhSbzVGMHF5OUhFSnVRVm9sWllaOWkvSWhnCi9OeTAxNGlyc0dDd2xmd3pySENL
            d2dPck0yelZ4VGx5Q1E1QWRBYk9rdHMKLS0tICtTVzJTSEQwQ2xSa0xSRDdsTTIw
            RjZkeEoxUmhwZGwvditNVzlvRUQ1VncKbNEf43ZE+UARbptUpniFvR8lgkgymOhr
            P4+KUx14x0d7Bh8AupvRsyXf58Wx9AX1W0c/nY2e7zPJi4LiFr7n/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T16:56:38Z"
    mac: ENC[AES256_GCM,data:dgmGG4MpqW8gyLCUzA96aUys30alUM7EzMJ5BwyjFQFJVE2rUw/xNf1A62Iy/9RGbkjmyhtjbiTsjIRdk3LUj1YjlPm32pfD93sfZh2sHoPO8kxkvpcdJwlODgO41opAcmE52Y6usv/2YwP4nk0H9X/KltRHMnjxjCi2IXWHaV4=,iv:awO/dHam1nM5Nnk8/jGyYMVUcV6VtOX1o7zvlLXr80s=,tag:XyHS3BGfa67HqRZavdvuNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
