# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app newt
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      newt:
        replicas: 1
        strategy: RollingUpdate

        containers:
          app:
            image:
              repository: fosrl/newt
              tag: 1.2.1
            env:
              PANGOLIN_ENDPOINT: https://pangolin.${SECRET_DOMAIN_FBE}
            envFrom:
              - secretRef:
                  name: ${APP}-secrets
    service:
      app:
        ports:
          http:
            port: 80
    serviceMonitor:
      app:
        endpoints:
          - port: http
    persistence:
      data:
        existingClaim: newt-data
        globalMounts:
          - path: /opt/newthome/data
      conf:
        existingClaim: newt-config
        globalMounts:
          - path: /opt/newthome/conf
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN_LOCAL}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    # ingress:
    #   app:
    #     enabled: true
    #     className: internal
    #     hosts:
    #       - host: &host newt.${SECRET_DOMAIN_LOCAL}
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #             service:
    #               identifier: app
    #               port: http
