apiVersion: v1
kind: Secret
metadata:
    name: newt-secrets
    namespace: network
stringData:
    NEWT_ID: ENC[AES256_GCM,data:pbGZmeZmQ47jESQgSW7X,iv:6U8aWgJCvVbrBiUFJCPgYv9dJw/G/WUNgern9TevgWc=,tag:Edk661Qx+5eBZwWX5Kd0VA==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:1OiYeiuKPM9bnur/OTyk2ZhAMWfwQ/q+xorLgFzTxZ/cHHbYz0L/CEjbVUowbY6C,iv:fJXLIffubZRdlFvsXU28DmUdISdCOVadVp8WU/sIIFc=,tag:kSnSok3I6Ttj/sHABvPnpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T01:32:40Z"
    mac: ENC[AES256_GCM,data:lle1BeTNp/plQJt+pkbNEjK3Xd45mBiyO3RqTdFltvnVIGWSc+/+U6MlAtuYhYDAisteOeA44Y+ehyDpWDSBOYQfxBOASQyfuoDCCG1dt6b+3fK+iN3XEwb2yZm7QFNGAXIYPwvDMllW/InnMUJEG6QBukYWtpQlRi3sidXS2pE=,iv:REtMA8yJ1/dtmSC19lLpmPzVYa3OUlwmBfE2CR0LToo=,tag:dXTpMUK/d7rnNdsfM6Qpeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
