---
apiVersion: v1
kind: Pod
metadata:
  name: my-csi-app
  namespace: storage
spec:
  containers:
  - name: my-frontend
    image: busybox
    args:
    - sleep
    - infinity
    volumeMounts:
      - mountPath: "/data"
        name: my-do-volume
  volumes:
  - name: my-do-volume
    persistentVolumeClaim:
      claimName: csi-cephfs-pvc
