apiVersion: v1
kind: Secret
metadata:
    name: plexplay-secrets
    namespace: media
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:UOXgvvZNairCK27RiySZgshGcsANvZVVdvLPu0h6H+ovU/7sIBoWDVXFNSbmTbwAE8ZUu4QdCzwj9yBd/5R3Pw==,iv:jCsbUQ7NwWKkbfIIQTx0o032JVdNf5SpoS+OZHeNDWE=,tag:0gxUCccpioy8M6aV0x1r1A==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:zAPFgr5IEdKcyW/WN7D/IVWh3mG0hHYnCMkSV2Eq1xubsCY=,iv:wUkk3o6hFo85o422QKqRuszI8pmlhCGY2JOOtemYoo4=,tag:CGlR3jBMfTF8wpbMR2ltZg==,type:str]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:91j2xpzvATzfNQhtI1hQ60EbmQOLmA==,iv:oweJbwOVS9pICsn3J+5tEEN/67cIeMWheGJuX1qtQVg=,tag:Ee0Eu8sBLht9/1wbzdFI/Q==,type:str]
    OPENAI_MODEL: ENC[AES256_GCM,data:qtwsv+0bqNs00GIuvTdH+qsjkQ==,iv:3oEXMH/5lRwqIpKxvd6ZH3VzW4xj+0C6vx/1y0+OUSM=,tag:MjM+4FaCFEM+o+ywUbNBaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cjhDaWhNdDEvUDJ3TEN6
            UkN4WXVpak0rTEo4MW1SeHZMa200aFBxZUFvCjQwb2llMENCS3lDWDFqNyszZ1R4
            a1E3MjZDQkFqa0orRkMyNkdtYlR3Sm8KLS0tIDJzTlc0MGdhNmkrSmlrVTBNdFZF
            WE5Ma1VQRkVmaXJ1c3I4WFo0eG14bTgKw5TLm+0LU04KAme9HSGlHPzyYXgfhGAi
            AFUPJfYOIQtfK+jzCMLtB2mitwOal3cATy/xt1nztgEWWN118NET6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T19:00:17Z"
    mac: ENC[AES256_GCM,data:4VLRX1C4D8A578fahqx1VTE784pv/7t6oJQW2iJqcZgQdu2k6jGOWPj3lYP4so50T6wHMdp9wSYo9ZSXSWHPt+wLEid+xnbDkLYzJQlCrZ2maZ363N5oPEkZ+khiiMTe5ASnjl3gDz49zdTSrfyOoHbYr12Qz1RhI2pB4nWFJHg=,iv:VWABNESUAY8Yg3UtDvU9+LGtTGdmBDSJwE4HTfBy9v0=,tag:ASgvCA0g8j+05CXuVEnGTQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
