---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-server
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    controllers:
      immich-server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.134.0
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 2000Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-config
            env:
              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-pguser-immich
                    key: uri
    service:
      main:
        controller: immich-server
        ports:
          http:
            port: &port 2283
    route:
      main:
        enabled: true
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
          - photos.${SECRET_DOMAIN}
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port
    persistence:
      data:
        enabled: true
        existingClaim: immich-data
        globalMounts:
          - path: /usr/src/app/upload
