---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app serene-pub
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: ${PUID}
        runAsGroup: ${PGID}
        runAsNonRoot: true
        fsGroup: ${PGID}
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      serene-pub:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/doolijb/serene-pub
              tag: 0.5.1-beta
            env:
              SERENE_PUB_DATA_DIR: /data
              HOST: 0.0.0.0
              PORT: "3000"
              SOCKETS_PORT: "3001"
              PUBLIC_URL: https://serene.${SECRET_DOMAIN}
              TRUSTED_PROXIES: private
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 3000
                  periodSeconds: 5
                  failureThreshold: 30
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 3000
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 3000
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
    service:
      app:
        controller: serene-pub
        ports:
          http:
            port: &port 3000
          socketio:
            port: &socketio 3001
    route:
      app:
        enabled: true
        hostnames:
          - "serene.${SECRET_DOMAIN}"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /socket.io
            backendRefs:
              - identifier: app
                port: *socketio
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        existingClaim: serene-pub-data
        globalMounts:
          - path: /data
