# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:1ym1KSIuol7ovWvPsw/qSqsgYfmiWZRkHuAeMwJ6Is3/qQv0RPzUBQ==,iv:7FXhszpyEHoI3rcgdym2e+wYmNh0WtNjLGk9OMNWw1Q=,tag:F7EinGpw58DkykEWC3B+aw==,type:str]
sops:
  age:
    - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdE5FUjRoRE9uNmFmSzNG
        TWJwZFJ5STUyUGltNU1vSE40ampYdjNBbTJJClNTUUpqcmFIRmowMEFGbXo0YVFU
        akdhN0hKUTVlUlFkL1RiQW82SjJZbUEKLS0tIHBtRE9QWjMyaHpiYm5MYnlGL21Q
        SFY4ampPMDBZRS9STnFTOWxlTzNOaW8Kftwkz1j56GI+U6y415ojLjvesTVrQ43T
        qzYGcDVSAOa1e2T5ATiCQGSSctZwQpiyHngNJAO4bL4YQpBkN1F9rQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T20:53:03Z"
  mac: ENC[AES256_GCM,data:bFzFORvkyIXnOomGA1ll0CuX/O9h8t7BVcH/KLkqG99jlSD2LmauMAI/7LqH5IgPQ8auwFVaaoBFzlsMZVhq14zm+vWX5gJU7qiSp5vyCoAfatlasumQVlsLvYJAR1BAyHosZCU64IUI/22TD7D5K8yrY5oIdMWzPc1RzufuHsE=,iv:7xHPsJhL4GemAAsqVcVMf0X3aAC5M3jMoAqluxk10ZM=,tag:/OqY+5iPyjvDDsHwegGEng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
