apiVersion: v1
kind: Secret
metadata:
    name: dungeon-endless-secret
    namespace: home
stringData:
    APP_ENCRYPTION_KEY: ENC[AES256_GCM,data:TkljybewOsMBH76r4Eo3rDmdqHahs9KYMNgWNX644WgS+rZes7sFLKmkM7CXL28Mdm7/P5OMtt0BKpqf94DZIw==,iv:hNmG3fOl3hbHpxmtwU9+TRy1UeZ3hBep0PuWyWg3cao=,tag:3WZZzv8VmkuY6LKAkZK+yg==,type:str]
    BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:lsAXUGc=,iv:NdVABcxhttERtKgrqq4nkEbUeU0u+tnjQ4X+Mq3LV20=,tag:gKdZP11BcpWAXqsfhI/Ygg==,type:str]
    BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:/NwDBdAxy1l964ts3w==,iv:HnCoPzZpdtV5ULEGbjVwtbO4VTOjdLDIoONOW2Ism+8=,tag:UKVygeQmZ/4qb5flIoRgPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNVRYdGtYdHI4MjFQUzRs
            SzhjZzM1dFlQei9qSTJFeVZ1VTNEa01JekJJClZiNm1TaXh4emcrWTFKc09VTU5z
            a0dQWnBkcGk1Z1pldEswVkgwQzJESW8KLS0tIE95V1dBNWo1aGN6aVdwTjM2b0xV
            bXVvdVNHSW9lL2dacytCeFh0RDB5MHMKLzjuJNIIvUEejqVFlLOlkjcr6FNww6e8
            hzzyZA+kzCpf3YTdjtTSg9cx8Tp2VxhAw1PhKtykHLKlnwO/y3KuNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T01:24:16Z"
    mac: ENC[AES256_GCM,data:jO3pkenLm8jZFwYCv6aeuytCk2IeIkhBm64Kl1xgZkNjgVzGRpbIBBD9/Ueuh24MucceFDPCUuXMfZ/HgSw6ilVyvWb2eZBcz9ENrGEcba4XQbYBCJbbE35wHMwVHCfncKJBT+4ezxO5cL3NlIVohvVK214PoZQEuqYDNpyqB6c=,iv:byOB9XkUDI3dBctCEHyO9QgMfR1QuqE2PF+wLn6b+sY=,tag:zOB7Zg2zZRj1CBGH094dDA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
