---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app toolhive-operator-crds
  namespace: &namespace ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: toolhive-operator
  interval: 1h
  path: ./kubernetes/apps/ai/toolhive/crds
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - kind: ConfigMap
        name: cluster-settings
    substitute:
      APP: *app
      NS: *namespace
      GATUS_DOMAIN: ${SECRET_DOMAIN_LOCAL}
      GATUS_SUBDOMAIN: *app
      GATUS_PATH: /
      GATUS_STATUS: "200"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app toolhive-operator
  namespace: &namespace ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: toolhive-operator-crds
  interval: 1h
  path: ./kubernetes/apps/ai/toolhive/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - kind: ConfigMap
        name: cluster-settings
    substitute:
      APP: *app
      NS: *namespace
      GATUS_DOMAIN: ${SECRET_DOMAIN_LOCAL}
      GATUS_SUBDOMAIN: *app
      GATUS_PATH: /
      GATUS_STATUS: "200"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app toolhive
  namespace: &namespace ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: toolhive-operator
  interval: 1h
  path: ./kubernetes/apps/ai/toolhive/config
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - kind: ConfigMap
        name: cluster-settings
    substitute:
      APP: *app
      NS: *namespace
      GATUS_DOMAIN: ${SECRET_DOMAIN_LOCAL}
      GATUS_SUBDOMAIN: *app
      GATUS_PATH: /
      GATUS_STATUS: "200"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  timeout: 5m
