---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app litellm
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      litellm:
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: &secret litellm-secrets
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/berriai/litellm
              tag: main-v1.72.6-stable
            envFrom:
              - secretRef:
                  name: *secret
              - secretRef:
                  name: ${APP}-db-secret
            args:
              - "--config"
              - "/app/config.yaml"
    service:
      app:
        ports:
          http:
            port: &port 4000
    serviceMonitor:
      app:
        endpoints:
          - port: http
    route:
      app:
        enabled: true
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        #annotations:
        #  external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config-file:
        type: configMap
        name: litellm-configmap
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
            readOnly: true
