# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:PviVNMAk7rsBobkYidKyAXIkG6RoJQsbE718/BNUrMo=,iv:EtXNtV24+cyKtwJhxvcb+XEFIy2qT9c57+9UMK3Cm44=,tag:SKqlrjVwczcDVBsw6+dahg==,type:str]
sops:
  age:
    - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V0dUaFRLMWh5ZCswQkQ1
        cU5TZm11OWUwcGZtZTdtdU41OThad2dUS3drCjl1MjVYWVNGNThneFlkdWJPY2sx
        Tk1LUHZ1MUhOOFBFZjllOXM0VTdNUmMKLS0tIGZ1ZkZjenBCKzZLMDI4T3ZUNWI4
        MElRNkU2SXNnSUFrL1o3YjJ0NGxLUWsKELAvYzQK5Oi7B6njCA9u2wqWfHUpFCs8
        ujjwPRmzxiH0GaNCVnwLMec95vcMSVbdMQYvXSdKAFYrXOqK/4xG3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T17:04:08Z"
  mac: ENC[AES256_GCM,data:9O1qrR2IofxI7vSBqoxoYrtihfts46y6PGIv4ngI05OKPGmHYQhBe5rKMxCF6WDwYZNICYAd+KLk2CWW5hwDSxkLrvxICuFMpRw3f7ZdbE3X/bzshSDwm8r1C8Z1u1qJX4Ew53YGVelZYSUxcNZiUtghvU5QohTBUZnN8Agk+nQ=,iv:0A+ED+FaNtna8HA3ZnoYyhh/ZSbKr3VQcRJZnkwUrw0=,tag:xJoT9E94eOHYBJjIhu1pSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
