---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplex-xftp-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-sc
  volumeName: simplex-xftp-config-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: simplex-xftp-config-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: simplex-xftp-config
    namespace: messaging
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-messaging/simplex-xftp/config
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: simplex-xftp-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplex-xftp-state
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 9Gi
  storageClassName: csi-cephfs-sc
  volumeName: simplex-xftp-state-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: simplex-xftp-state-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: simplex-xftp-state
    namespace: messaging
  capacity:
    storage: 9Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-messaging/simplex-xftp/state
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: simplex-xftp-state

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplex-xftp-files
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 90Gi
  storageClassName: csi-cephfs-sc
  volumeName: simplex-xftp-files-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: simplex-xftp-files-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: simplex-xftp-files
    namespace: messaging
  capacity:
    storage: 90Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-messaging/simplex-xftp/files
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: simplex-xftp-files
