apiVersion: v1
kind: Secret
metadata:
  name: simplex-xftp-secret
  namespace: messaging
stringData:
  PASS: ENC[AES256_GCM,data:4I1q2hQY5QUpz6eEe6/H/64d1nFemCcoCYV2YJjxmwaIMGBFQL46sayLaaC2cjCo,iv:BbxiHkoC/ElepMfDOYbxznCVyc6zOnZy09P0c3A/d98=,tag:nt3zFQq1IRPTCEeebyKSXw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU2F4dmNTK0RGRkR0Tmdy
        R0tmbmZKUUtnMXpuclZ4djlPbTdNQXJNcEZZCjBOMysxbTVGRDdQQldmOGNZRUR0
        cFd1azBJdDZ3S1JnK2xiV2NxS3o4NVkKLS0tIGxWWU1DK1pSU3FDT3ZSUzlSaFJs
        STR4MjZ6S2ZXWGxoNWszNFdvb1c4TGcKdROiJWan4sOTh9sOPRUhux0BiBU4dNlf
        Ig+TmWak+Wvs2f7D9q/SU5KaXZeHNOzgC4PSnUYEEM9jY2It79xhvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T18:01:28Z"
  mac: ENC[AES256_GCM,data:bKHuaDixUf6Ue9jo4rOVasBHiJTOe0B0NiqsfELJYw+sHKdT40H4e68YNtf48A53Xl9/o7M70VeCD4FnzSW9M22R6dXhYHS+kbLVHPd8fgoMLY5HmEQOQ5+Za3neO/DS0JKkPSXzvQwZa7x5tHcRX49BK6jiFAKRMkosrXMz7xA=,iv:ayxZI9+/peNJzRtPWLsQ9v3KYWDtiY6FAhK0DHTQJzQ=,tag:7gq0x6N7r2QvtRbEgxzqow==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
