apiVersion: v1
kind: Secret
metadata:
    name: mealie-secrets
    namespace: home
stringData:
    #ENC[AES256_GCM,data:54vjyk2YZdcKY7Mef5YOKU4KTXWP9r62iyB93eQjCAtQhuk18CT/Se2vyRPzg6ZO404xrMA3zR1QJBAA1oUntWp0v7oj7z8Rrs2kb7TB4TU//5DjFGlANIyxlKPEo7D+rsGXf8Y6zrj8VxME42KZi2bSaZZ3QkY7elv1tsBk/YSSMHMsaRARqBbnNdHoNeukflfmlRrU0bNcwSMpr0gMF87NOTmha2/O6Sk7yZegFVJTptSW,iv:pXwPDiWEPCFjBngAjeg0qFOcke+01zXfXGP/oVkUnYU=,tag:N557JHxccKoKLu0cXyJuWg==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:m07MHi+B0ckpgw==,iv:1a9T+lBtv9F9WhhhIMrK+TQqE3RAnr5kwplGgwRQe3c=,tag:DmnJKteGRYXZaULGdLwOTg==,type:str]
    OPENAI_MODEL: ENC[AES256_GCM,data:QMIrbMKExFemgpkpSzaB4fhP3JAt+3Gr6gPKHBIf3zjzpJDx,iv:anTwR2GxkS5JyW0RrAQzOr3v+HC8LjcoR+qTGgBb5CA=,tag:06nb7Qac3nO2NkoYTOvPsg==,type:str]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:gO+6Dw7OXaEZmOvA+1GN8qiv+hIy/gTf,iv:p+ZfT0oUkaS/P6dZCgojZaZ4UJIzIffyngaNpZZQi/k=,tag:tY+tkCDa2YxEnCWWOAXSPQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:eCdQ5O1IhvNaPpO4e7X7tK7RfsxcHgrBkgZfiI/nURIhIAVCYjpM5Q==,iv:7gW0HqSBQpJLnF+26McizJ0J7DMmYvhFMppMeMIkNmE=,tag:h01z3NnPDv7rDFPogh0tGQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:xhVsSMAJjq9LpvuR4OXPzeSV6TUWnvoxjurpLvElRzdcM2wUNQettE2K0tEwo+mTY4RV/8naEf7DeiDDoC1kUlHoi7cj4tlCuzt10g2I1N7x5/eN4+LFeDJ39OiCrjlpSqf7xAdrbC9PWLYJceuCxyFAbuPFLPWHKvPC69D227U=,iv:FzjvJ+94S1nbK+UA6xWZTsNSyZ5RP6klfzEV5nugVPI=,tag:w3DQxV/UJCRc7S/ywMZU0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T14:19:25Z"
    mac: ENC[AES256_GCM,data:BEqSNHfOvVYi7BpoLcspM4OefPw9uB8XwsF1MizLe0kJwiyyxez0FsZmemEzocfOzQB2KJ73wdrY6g/citHKvZHPhg0r9Y8DlTsdxI8XwCLMTjGaMhcA07RjBjnTpeYI351I2Ipzpy12B2uuKaaVldIWGFQLBC1P9I8RIr866xE=,iv:n0iSlaaaLtwgAm09j3uMlAnz7JjM13Ne2l1W+0zhjNA=,tag:i2MX7sPEn9vXBJMrcQfihg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
