apiVersion: v1
kind: Secret
metadata:
    name: mealie-secrets
    namespace: home
stringData:
    #ENC[AES256_GCM,data:54vjyk2YZdcKY7Mef5YOKU4KTXWP9r62iyB93eQjCAtQhuk18CT/Se2vyRPzg6ZO404xrMA3zR1QJBAA1oUntWp0v7oj7z8Rrs2kb7TB4TU//5DjFGlANIyxlKPEo7D+rsGXf8Y6zrj8VxME42KZi2bSaZZ3QkY7elv1tsBk/YSSMHMsaRARqBbnNdHoNeukflfmlRrU0bNcwSMpr0gMF87NOTmha2/O6Sk7yZegFVJTptSW,iv:pXwPDiWEPCFjBngAjeg0qFOcke+01zXfXGP/oVkUnYU=,tag:N557JHxccKoKLu0cXyJuWg==,type:comment]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:WBhuRh52kzIo0BnN8dw4acpXDg0E7ZA=,iv:C++E8qWFhSYEnRu3LybLbaa/mOHp3nru9HhuSnL0t6s=,tag:HHSNcI6EsyjHtod4nkVhWg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:gr7QYk9X0TbDWd6km7WCuct33zFBEkObFK7oYqVM8O3i5X8=,iv:jmyJTSHeFFrLzgMGW6EYMTRAGEN5po3vYtnNNvjcq7c=,tag:YsFJAkDXj60cE90297dGOA==,type:str]
    #ENC[AES256_GCM,data:t3ppDx+vrWTCneZJHDpXc4vHg7OgT7Pj9r0YOEtGtAkGhtqVY3Qz0GAoH7+wB3MPltCp9lv1u06ADVo8DPtSMqZLGLqUNsScKlMi+uxmdjYaXPs3fQFbGw==,iv:VrVyoYPct/nd/P7i2mjTgJ51Ndx7V59uwy71X5osWis=,tag:uKOOnk+KoU3CVuB+Zh5+GA==,type:comment]
    OPENAI_MODEL: ENC[AES256_GCM,data:HrZVAtPy1WuspkvjfQ==,iv:/iEm9uArgMnp8FSLsyoSQBuxaOc+fIFzEKGUwI8rsVQ=,tag:6xFS5ScTJRmV29TeHqVYRA==,type:str]
    #ENC[AES256_GCM,data:EbfHsnR1ZdzkaD7RIpzXsDfIeabeIIu2lf8+0txiflkiMB8foOpiNPjBfrqUXzPYr/XjOMES,iv:FHAoGr37JTZthztXSU1EWWsU8szLteGsXK6ElRa0phU=,tag:knEknpXk36CAE15pwv2JYA==,type:comment]
    OPENAI_AUDIO_MODEL: ENC[AES256_GCM,data:133v6B+A6LmJU+sIVjlrqg==,iv:voNkT30tU0bwA9wKcWkBJHedR7aGrphIDf0BOXSJtP0=,tag:TaEvFmr8rqBD+IRjUcTV2g==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:eCdQ5O1IhvNaPpO4e7X7tK7RfsxcHgrBkgZfiI/nURIhIAVCYjpM5Q==,iv:7gW0HqSBQpJLnF+26McizJ0J7DMmYvhFMppMeMIkNmE=,tag:h01z3NnPDv7rDFPogh0tGQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:xhVsSMAJjq9LpvuR4OXPzeSV6TUWnvoxjurpLvElRzdcM2wUNQettE2K0tEwo+mTY4RV/8naEf7DeiDDoC1kUlHoi7cj4tlCuzt10g2I1N7x5/eN4+LFeDJ39OiCrjlpSqf7xAdrbC9PWLYJceuCxyFAbuPFLPWHKvPC69D227U=,iv:FzjvJ+94S1nbK+UA6xWZTsNSyZ5RP6klfzEV5nugVPI=,tag:w3DQxV/UJCRc7S/ywMZU0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T13:08:41Z"
    mac: ENC[AES256_GCM,data:9Uty7wJSGjm+KjwXFxmIbUHOxiOpkWf08OKX7oPJQearEBZfFv8G1Mo1mqZn6D6tTFbmBM7zKoadzOWdZ8D+1ee9CUu1YiRiGZVtwIGQV+L8CA4ceOvLdGrtRKSf2iif87xB7uLRDOYvRN/7eUf9h/vCqJwAXzPShlztEMUtYl0=,iv:vLkksW0lceso/izM2ETErK9H9Y5Ar0HLs/U90hgjsZ8=,tag:BJOhyTnQhkPNIUQ4H5M+vw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
