---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sabnzbd
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
  - ../../../../components/gatus/internal
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: csi-driver-cephfs
      namespace: storage
    - name: csi-driver-smb
      namespace: storage
  interval: 30m
  path: ./kubernetes/apps/media/sabnzbd/app
  postBuild:
    substitute:
      APP: *app
      NS: *namespace
      DB_NAME: *app
      DB_USER: *app
      GATUS_DOMAIN: ${SECRET_DOMAIN_LOCAL}
      GATUS_SUBDOMAIN: sab
      GATUS_PATH: /
      GATUS_STATUS: "200"
      GATUS_GROUP: internal-media
      GATUS_PROTOCOL: http
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: fuzzlab-gitops
  timeout: 5m
  wait: false
