---
apiVersion: v1
kind: Service
metadata:
  name: home
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  #externalIPs:
  #  - ${HOME_ADDR}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: home
subsets:
  - addresses:
    - ip: ${HOME_ADDR}
    ports:
      - port: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: home-1
  labels:
    kubernetes.io/service-name: home
addressType: IPv4
ports:
  - name: http
    addProtocol: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - ${HOME_ADDR}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN_FBE}"
  name: proxy-home
spec:
  ingressClassName: cilium
  rules:
    - host: &host home.${SECRET_DOMAIN_FBE}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: home
                port:
                  number: 80
  tls:
    - hosts:
        - *host
      secretName: ${SECRET_DOMAIN_FBE}-production-tls
