---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
components:
  - ../../components/common
resources:
  - ./device-plugin-operator/ks.yaml
  - ./gpu-device-plugin/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./nvidia-device-plugin/ks.yaml
