---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
components:
  - ../../components/common
resources:
  - ./beginnings/ks.yaml
  - ./blog/ks.yaml
  - ./codex-web-test/ks.yaml
  - ./evolution-rpg/ks.yaml
  - ./ha-ocr-schedulerr/ks.yaml
  - ./homebox/ks.yaml
  - ./km/ks.yaml
  - ./mealie/ks.yaml
  - ./secrets.sops.yaml
  - ./stellar-tails/ks.yaml
  - ./teslamate/ks.yaml
  - ./tg-vid-converter/ks.yaml
