---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sonarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: csi-driver-cephfs
      namespace: storage
    - name: csi-driver-smb
      namespace: storage
  values:
    controllers:
      arr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: 4.0.15.2940
            env:
              TZ: ${TIMEZONE}
              SONARR__APP__INSTANCENAME: sonarr
              SONARR__APP__THEME: dark
              SONARR__AUTH__METHOD: External
              SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
              SONARR__LOG__DBENABLED: "False"
              SONARR__LOG__LEVEL: info
              SONARR__SERVER__PORT: &port 80
              SONARR__UPDATE__BRANCH: develop
              SONARR__POSTGRES__HOST:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_HOST
              SONARR__POSTGRES__MAINDB: "${DB_NAME}"
              SONARR__POSTGRES__LOGDB: "${DB_NAME}-log"
              SONARR__POSTGRES__PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_PASS
              SONARR__POSTGRES__USER:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_USER
              SONARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: cluster-media-secrets
                    key: "SONARR_0_API_KEY"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 4096Mi
    defaultPodOptions:
      securityContext:
        runAsUser: ${PUID}
        runAsGroup: ${PGID}
        runAsNonRoot: true
        fsGroup: ${PGID}
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: arr
        ports:
          http:
            port: *port
    # route:
    #   app:
    #     hostnames:
    #       - "{{ .Release.Name }}.${SECRET_DOMAIN_LOCAL}"
    #     parentRefs:
    #       - name: internal
    #         namespace: kube-system
    #         sectionName: https

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      lcl:
        enabled: true
        existingClaim: lcl
        globalMounts:
          - path: /lcl
      downloads:
        enabled: true
        existingClaim: lcl-downloads
        globalMounts:
          - path: /downloads
