apiVersion: v1
kind: Secret
metadata:
    name: model-hotel-secrets
    namespace: cloud
stringData:
    MASTER_KEY: ENC[AES256_GCM,data:s73JKVpNpfDlEuNbUh/Rgj6fEJBTc4cCobcgLxOTp8ZMDkc4/AqG4a0xL9aQ9tbfe0ZZbCcgTV3yVHT6TauHfQ==,iv:QNeOIdkipyTZm697JNKVBbEmQuIMP7xjUxOVbL20lWU=,tag:h/rn+jdsOGB3Rbts9uXeng==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:Ix+Gce12M2GANtBmuSmDKxT8fYG1sSqELdJhw3QSzaZQJ8kK9CYvYt6ctLFOoUpD8YfEhxkx8PdHGO2GbHJGgw==,iv:9FzqMVIU/BwmvHj+uGU8spOTGvfwsr1m4D4cl+MbdG0=,tag:mmYznIDLnUCi8/+jGMkMWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T16:39:14Z"
    mac: ENC[AES256_GCM,data:eySSyWibXV3j9GVD7aC5FwUMx7xip0EEC6U3+O3fNM4NUSQGhEIlXYGe6qFBatNOhxLYxB06fb6cmssrg1ZmfSs4/2bcX0Ud52H0huwTKfzBb07acCy7Z7SrToW8GDJQhVehrkShBkAyo9Jxp36N42BFy85RniGbUNHXatMmJQo=,iv:1yutLv1lcgIhr+EaWWvl9JtaVk/q0YF3ks3I2ZD/rgQ=,tag:IEJqPSYQk2nIOoi7UQYKwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
