---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app readarr
  namespace: media
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: csi-driver-cephfs
      namespace: storage
    - name: csi-driver-smb
      namespace: storage
  values:
    controllers:
      arr:
        pod:
          securityContext:
            runAsUser: ${PUID}
            runAsGroup: ${PGID}
            runAsNonRoot: true
            fsGroup: ${PGID}
            fsGroupChangePolicy: OnRootMismatch

        containers:
          main:
            image:
              repository: ghcr.io/home-operations/readarr
              tag: 0.4.18.2805
            env:
              TZ: ${TIMEZONE}
              READARR__APP__INSTANCENAME: readarr
              READARR__APP__THEME: dark
              READARR__AUTH__METHOD: External
              READARR__AUTH__REQUIRED: DisabledForLocalAddresses
              READARR__LOG__DBENABLED: "False"
              READARR__LOG__LEVEL: info
              READARR__SERVER__PORT: &port 80
              READARR__UPDATE__BRANCH: develop
              READARR__POSTGRES__HOST:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_HOST
              READARR__POSTGRES__MAINDB: "${DB_NAME}"
              READARR__POSTGRES__LOGDB: "${DB_NAME}-log"
              READARR__POSTGRES__PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_PASS
              READARR__POSTGRES__USER:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_USER
              READARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: cluster-media-secrets
                    key: "READARR_0_API_KEY"
            resources:
              requests:
                cpu: 18m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      main:
        controller: arr
        ports:
          http:
            port: *port
    # ingress:
    #   main:
    #     enabled: true
    #     className: internal
    #     hosts:
    #       - host: &host "readarr.${SECRET_DOMAIN_LOCAL}"
    #         paths:
    #           - path: /
    #             service:
    #               identifier: main
    #               port: http
    #     #tls:
    #     #  - hosts:
    #     #      - *host
    persistence:
      config:
        enabled: true
        existingClaim: readarr-config
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      lcl:
        enabled: true
        existingClaim: lcl
        globalMounts:
          - path: /lcl
      downloads:
        enabled: true
        existingClaim: lcl-downloads
        globalMounts:
          - path: /downloads
