---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app prowlarr
  namespace: media
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: csi-driver-cephfs
      namespace: storage
    - name: csi-driver-smb
      namespace: storage
  values:
    controllers:
      arr:
        pod:
          securityContext:
            runAsUser: ${PUID}
            runAsGroup: ${PGID}
            runAsNonRoot: true
            fsGroup: ${PGID}
            fsGroupChangePolicy: OnRootMismatch

        containers:
          main:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.0.0.5094
            env:
              TZ: ${TIMEZONE}
              PROWLARR__APP__INSTANCENAME: prowlarr
              PROWLARR__APP__THEME: dark
              PROWLARR__AUTH__METHOD: External
              PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses
              PROWLARR__LOG__DBENABLED: "False"
              PROWLARR__LOG__LEVEL: info
              PROWLARR__SERVER__PORT: &port 80
              PROWLARR__UPDATE__BRANCH: develop
              PROWLARR__POSTGRES__HOST:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_HOST
              PROWLARR__POSTGRES__MAINDB: "${DB_NAME}"
              PROWLARR__POSTGRES__LOGDB: "${DB_NAME}-log"
              PROWLARR__POSTGRES__PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_PASS
              PROWLARR__POSTGRES__USER:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_USER
              PROWLARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: cluster-media-secrets
                    key: "PROWLARR_0_API_KEY"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      main:
        controller: arr
        ports:
          http:
            port: *port
    # ingress:
    #   main:
    #     enabled: true
    #     className: internal
    #     annotations:
    #       #external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
    #       hajimari.io/icon: card-search
    #     hosts:
    #       - host: &host "prowlarr.${SECRET_DOMAIN_LOCAL}"
    #         paths:
    #           - path: /
    #             service:
    #               identifier: main
    #               port: http
    #     #tls:
    #     #  - hosts:
    #     #      - *host

    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      lcl:
        enabled: true
        existingClaim: lcl
        globalMounts:
          - path: /lcl
      downloads:
        enabled: true
        existingClaim: lcl-downloads
        globalMounts:
          - path: /downloads
