---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app telegram-oauth
  namespace: &namespace security
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
  - ../../../../components/gatus/external
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: authentik
      namespace: security
  interval: 30m
  path: ./kubernetes/apps/security/telegram-oauth/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - kind: ConfigMap
        name: cluster-settings
    substitute:
      APP: *app
      NS: *namespace
      GATUS_SUBDOMAIN: *app
      GATUS_DOMAIN: ${SECRET_DOMAIN_FBE}
      GATUS_PATH: "/oauth/authorize"
      GATUS_STATUS: "400"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: &ns security
  timeout: 5m
  wait: false
