# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:pQZNO1JhJxPfYqGadBJrwkGHL1uTUcDYdjbaibj/f5wG+xj0Pjtry4Z/KPS9W8nOf/f+loFcO87xX6baYynhzG22o5AUyToFFD7GKKx4hvrW8gSNxLpnn8CUABS90woQsCMwano+IdqNJeoSTZm7Er7iHKSVdaDVZ0RIJwn58dODji77X3sEsSGAf0zIw8ImfAsrKP9E4ySkd+yzVVE191pFtAhcLX+2VdZ9aE0c2w/QB0Ja,iv:HKcLF/3dmIVb747+yL8HdCmpcLSEpwBbZaogRpS93w0=,tag:HjsWVmWfWjGOJln65k/hqQ==,type:str]
sops:
  age:
    - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZHh4OWRkNEpnaSt2V3V1
        cjM1c0dEc3NyK0creUFnVGdVWHRzQWtpenhjClBibm1DV2xwSWo2czN2T296RFh6
        bllvZDhQb1FkMENMenNJVjRSRTF4VTAKLS0tIGVIaEU3VjlyaGlsZzFPRlhBT3Js
        aEtGRFd2UzR1MndwRTZnRS9DYUZnRU0K719ttl6P4Xr8wUrWJ3XK1F9We0z2sbWw
        vLKT4EUBRSSQAkA0mbR9aTaco80it9eiE2owM589oHAxzkbYgVAHpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T17:04:08Z"
  mac: ENC[AES256_GCM,data:akGst9ucwf8TxvpWI2wPrpWOmDrycR/oxoigoqoefIPF2zCpMxgyxHf2kxb1FB2YwYUb4pXGIz1lunZuRmzgteYDZ6z5o1Z351UcDIRxTSP8wpVHKjD6F/tDLUnd9BoOhbO2wVGbJq2OE8C8Pa+QgeLl05ZdZG7f0b6dHFrufjs=,iv:TETcp3HG8va7xjHHdi71Bsa4rgW1geVoORudyAkgcSg=,tag:yHuVYRL2fNOtocKocS+R2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
