---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app foundrydc20
  namespace: cloud
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      foundrydc20:
        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          app:
            image:
              repository: ghcr.io/felddy/foundryvtt
              tag: 12.331.0
              pullPolicy: IfNotPresent

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            env:
              TIMEZONE: ${TIMEZONE}
              CONTAINER_CACHE: /data/container_cache
              CONTAINER_PATCHES: /data/container_patches
              CONTAINER_VERBOSE: 'true'
              FOUNDRY_TELEMETRY: false
              FOUNDRY_HOSTNAME: &host 'dc20.${SECRET_DOMAIN}'
              FOUNDRY_LOCAL_HOSTNAME: *host
              FOUNDRY_MINIFY_STATIC_FILES: 'true'
              FOUNDRY_PROTOCOL: '4'
              FOUNDRY_PROXY_PORT: '443'
              FOUNDRY_PROXY_SSL: 'true'
            envFrom:
              - secretRef:
                  name: foundrydc20-secrets

    service:
      app:
        controller: foundrydc20
        ports:
          http:
            port: &port 30000
    route:
      app:
        enabled: true
        hostnames:
          - *host
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        enabled: true
        existingClaim: foundrydc20-data
        globalMounts:
          - path: /data
