---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/common
resources:
  - ./litellm/ks.yaml
  - ./openwebui/ks.yaml
  - ./sillytavern/ks.yaml
  - ./sillytavern-kip/ks.yaml
