---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: media
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: csi-driver-cephfs
      namespace: storage
    - name: csi-driver-smb
      namespace: storage
  values:
    controllers:
      arr:
        pod:
          securityContext:
            runAsUser: ${PUID}
            runAsGroup: ${PGID}
            runAsNonRoot: true
            fsGroup: ${PGID}
            fsGroupChangePolicy: OnRootMismatch

        containers:
          main:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 5.22.2.9862
            env:
              TZ: ${TIMEZONE}
              RADARR__APP__INSTANCENAME: radarr
              RADARR__APP__THEME: dark
              RADARR__UPDATE__BRANCH: develop
              RADARR__PORT: &port 80
              RADARR__LOG_LEVEL: info
              RADARR__ANALYTICS_ENABLED: "False"
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
              RADARR__POSTGRES__HOST:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_HOST
              RADARR__POSTGRES__MAINDB: "${DB_NAME}"
              RADARR__POSTGRES__LOG_DB: "${DB_NAME}-log"
              RADARR__POSTGRES__PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_PASS
              RADARR__POSTGRES__USER:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_USER
              RADARR__API__KEY:
                valueFrom:
                  secretKeyRef:
                    name: cluster-media-secrets
                    key: "RADARR_0_API_KEY"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 2048Mi
    service:
      main:
        controller: arr
        ports:
          http:
            port: *port
    # ingress:
    #   main:
    #     enabled: true
    #     className: internal
    #     annotations:
    #       #External-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
    #       hajimari.io/icon: movie-filter
    #     hosts:
    #       - host: &host "radarr.${SECRET_DOMAIN_LOCAL}"
    #         paths:
    #           - path: /
    #             service:
    #               identifier: main
    #               port: http
    #     #tls:
    #     #  - hosts:
    #     #      - *host
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      lcl:
        enabled: true
        existingClaim: lcl
        globalMounts:
          - path: /lcl
      downloads:
        enabled: true
        existingClaim: lcl-downloads
        globalMounts:
          - path: /downloads
