apiVersion: v1
kind: Secret
metadata:
    name: ha-ocr-schedulerr-secrets
    namespace: home
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:4SyoOJCc4kLP0tgOSLNiGjr152RUfOhYGm9Tm6MODBrpgQtLoS96oKdOGipvgQ==,iv:l0W5VnkRUgDTm5oPT2GPhJQ0TBlKFGJTotOUDs9dikw=,tag:Dk7KHrlr/OWqglluS1XJmA==,type:str]
    HA_URL: ENC[AES256_GCM,data:jaLSpOxxe4ZjlvGAJPu77Q==,iv:B5R0lu833z/oDVqfpe0TSiQlEBpgEk1P/cYML392qvk=,tag:WJTcO/MaOId7ZOptPpYFSQ==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:hMJLaHOlvgBsVAcVkXNeNO2zZLt3T1dRK41dbaZSbv+x31JhK6gIqNnMXxYaulTmB/gNurR5LfauQMZVyCiVMjmvgz7mh+apzQlCH4n/uyI0rIfMEEiZuSXjMRs9WyZzHb/KLJuGu4tKqKOBeGIXtKz3qTwPKMidNT6UPZw7Yceg9/sf+5eXTcRE062S7asM2yftFx6OpcVcC43Di7T0wz/vjM+XvnZLJ3CJtWlG6AwjH8j1tKAb,iv:9kEMge5x72p1toKOXnbHRdeObtac/5ZNejKhuQ7Zf7U=,tag:240QhQLhg3sF5hAPwIBcSw==,type:str]
    HA_CALENDAR_ENTITY: ENC[AES256_GCM,data:OqwtsPYZYr5YWmM9XQ/ILcmvM9SsTzOsKg==,iv:xQ8o6VGeTyLGU9vfjYWsmGCIhbq18XiFwEm7hz5LWSg=,tag:SEAym8L22qOT6RhXjkE6rg==,type:str]
    ALLOWED_CHAT_IDS: ENC[AES256_GCM,data:Srl/Gvk1xIvQC1HKQJA=,iv:oGpi31Agr2lTBqSDRpbQPinryWPqInzF+24HDC6Uvis=,tag:D+3zhKxzcXbxR2/t4gv7+w==,type:str]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:meaSdoLgMLcEHt9H1B410ccZyMmUWVZ2,iv:o/8h/wOkVohDewTB0zNz+pukClmsPwAfboaOe/Z4zTQ=,tag:RdYcVyyt9Ej92AejyxvTrA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:zhfmpb0yS3zPv94pFw==,iv:Wbkz7Ph1OVMqoZzxGjNckJmdz3P8j1ejjmJM2Tr2Xrc=,tag:tr8k67e/8iawfbsf72356A==,type:str]
    OPENAI_MODEL: ENC[AES256_GCM,data:J3RKlh7B6GgCIhOFVJ2g++2wXhKfGu9ctAmEXDh/R4oebTQ7,iv:dSd9QeMC2eL33zrNiBCybO2C50YWTPdA5boT0xjBoxg=,tag:2pzvwGoi+eVkXlNuNuqZdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T13:41:09Z"
    mac: ENC[AES256_GCM,data:sVwei1U8nracl2n3LQOcxF3ROwiW6gZVM1t0aDp1u5PrNJmt4SwfVaTroSkrx2U6ML95HYB4nlxAtsUw2HV+ZpHFzb2lMfdLWBLYV6JXnuu5qkZ2eIj8AUmG+lUNovEcgaZQcTEl0VAw2Bu24/5X6LKDN86kJ3GJHcySdhDNVHs=,iv:Lw6bV7nJU93dM3x9wD19sVdf/Hdt/qjl6TMHJn2XUxA=,tag:bfFYxutEud/jlmCTiKkycA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
