---
# Note: Gatus vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
web:
  port: 80
storage:
  type: postgres
  path: postgres://$${INIT_POSTGRES_USER}:$${POSTGRES_PASS}@$${POSTGRES_HOST}:5432/$${POSTGRES_DB}?sslmode=disable
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status

alerting:
  telegram:
    token: $${TELEGRAM_TOKEN}
    id: $${TELEGRAM_ID}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 5m

endpoints:
  # External DNS
  - name: ${SECRET_DOMAIN}
    group: external-dns
    url: https://echo.${SECRET_DOMAIN}
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
  - name: ${SECRET_DOMAIN_FBE}
    group: external-dns
    url: http://${SECRET_DOMAIN_FBE}
    interval: 5m
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: telegram

  # Internal DNS
  - name: Adguard 01
    group: internal-dns
    url: udp://${AD01_ADDR}:53
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: Adguard 02
    group: internal-dns
    url: udp://${AD02_ADDR}:53
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: Adguard 03
    group: internal-dns
    url: udp://${AD03_ADDR}:53
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  # Network
  - name: UDM-Pro
    group: Network
    url: icmp://10.0.1.1
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: USW-Pro-Aggregation
    group: Network
    url: icmp://10.0.1.3
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: USW-Ent-Bottom
    group: Network
    url: icmp://10.0.1.2
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: USW-Ent-Top
    group: Network
    url: icmp://10.0.1.4
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: USW-8-Lighting
    group: Network
    url: icmp://10.0.1.5
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: USW-Agg-Upstairs
    group: Network
    url: icmp://10.0.1.7
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: USW-Pro-24
    group: Network
    url: icmp://10.0.1.8
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: USW-Flex-Mini-Outside
    group: Network
    url: icmp://10.0.1.9
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: USW-Flex-Mini-Attic
    group: Network
    url: icmp://10.0.1.10
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: USW-Agg-Fuzz-Suite
    group: Network
    url: icmp://10.0.1.12
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: USW-24-Fuzz-Suite
    group: Network
    url: icmp://10.0.1.13
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: USW-Flex-2.5G-Foxbox
    group: Network
    url: icmp://10.0.1.14
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: U6-Ent-Lounge
    group: Network-AP
    url: icmp://10.0.1.20
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: U6-Ent-LivingRoom
    group: Network-AP
    url: icmp://10.0.1.21
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: U6-Ent-Garage
    group: Network-AP
    url: icmp://10.0.1.22
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: U6-Ent-Upstairs
    group: Network-AP
    url: icmp://10.0.1.23
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: U7-Pro-Foxbox
    group: Network-AP
    url: icmp://10.0.1.24
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram

  # Internal Services
  - name: Postgres
    group: Internal-Services
    url: tcp://postgres-ha.database.svc.cluster.local:5432
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: Redis
    group: Internal-Services
    url: tcp://redis.database.svc.cluster.local:6379
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram

  # Virtual Servers
  - name: Forge
    group: server-virtual
    url: icmp://10.0.2.35
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: Forge-Runner
    group: server-virtual
    url: icmp://10.0.2.31
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: Deluge
    group: server-virtual
    url: icmp://10.0.2.105
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: Notes
    group: server-virtual
    url: icmp://10.0.2.114
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: KMS
    group: server-virtual
    url: icmp://10.0.2.177
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: talos10011
    group: server-virtual
    url: icmp://10.0.100.11
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: talos10012
    group: server-virtual
    url: icmp://10.0.100.12
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: talos10013
    group: server-virtual
    url: icmp://10.0.100.13
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: talos10014
    group: server-virtual
    url: icmp://10.0.100.14
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: talos10015
    group: server-virtual
    url: icmp://10.0.100.15
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: talos10016
    group: server-virtual
    url: icmp://10.0.100.16
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: talos10017
    group: server-virtual
    url: icmp://10.0.100.17
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: talos10018
    group: server-virtual
    url: icmp://10.0.100.18
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: talos10019
    group: server-virtual
    url: icmp://10.0.100.19
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram


  # server-hardware
  - name: PVE64
    group: server-hardware
    url: icmp://${PVE_ADDR} # ssh://${PVE_ADDR}:22
    ssh:
      username: ${SECRET_SSH_USER}
      password: ${SECRET_SSH_PASSWORD}
    # body: |
    #   {
    #     "command": "uptime"
    #   }
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      #- "[STATUS] == 0"
    alerts:
      - type: telegram
  - name: PVE01
    group: server-hardware
    url: icmp://${PVE01_ADDR} #ssh://${PVE01_ADDR}:22
    ssh:
      username: ${SECRET_SSH_USER}
      password: ${SECRET_SSH_PASSWORD}
    # body: |
    #   {
    #     "command": "uptime"
    #   }
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      #- "[STATUS] == 0"
    alerts:
      - type: telegram
  - name: PVE02
    group: server-hardware
    url: icmp://${PVE02_ADDR} #ssh://${PVE02_ADDR}:22
    ssh:
      username: ${SECRET_SSH_USER}
      password: ${SECRET_SSH_PASSWORD}
    # body: |
    #   {
    #     "command": "uptime"
    #   }
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      #- "[STATUS] == 0"
    alerts:
      - type: telegram
  - name: PVE03
    group: server-hardware
    url: icmp://${PVE03_ADDR} #ssh://${PVE03_ADDR}:22
    ssh:
      username: ${SECRET_SSH_USER}
      password: ${SECRET_SSH_PASSWORD}
    # body: |
    #   {
    #     "command": "uptime"
    #   }
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      #- "[STATUS] == 0"
    alerts:
      - type: telegram
  - name: PVE04
    group: server-hardware
    url: icmp://${PVE04_ADDR} #ssh://${PVE04_ADDR}:22
    ssh:
      username: ${SECRET_SSH_USER}
      password: ${SECRET_SSH_PASSWORD}
    # body: |
    #   {
    #     "command": "uptime"
    #   }
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      #- "[STATUS] == 0"
    alerts:
      - type: telegram
  - name: PVE05
    group: server-hardware
    url: icmp://${PVE05_ADDR} #ssh://${PVE05_ADDR}:22
    ssh:
      username: ${SECRET_SSH_USER}
      password: ${SECRET_SSH_PASSWORD}
    # body: |
    #   {
    #     "command": "uptime"
    #   }
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      #- "[STATUS] == 0"
    alerts:
      - type: telegram
  - name: Home-Assistant
    group: server-hardware
    url: icmp://10.0.2.10
    ssh:
      username: ${SECRET_SSH_USER}
      password: ${SECRET_SSH_PASSWORD}

    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
  - name: PINODE00
    group: server-hardware
    url: icmp://10.0.1.60
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram

# Lighting controller
  - name: FPPMAIN
    group: lit
    url: icmp://10.0.7.10
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
