apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns-secret
    namespace: network
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:OvIGRgokaNf9iXCzJHk24kJqWYgEC5zUFAeGVXBE/qs=,iv:DkM1NQHz2FHmIbfLXXuwvrorYKIlXB4/ALpl/Y64ZBc=,tag:/NFagwL7140oQE/1uXEpEA==,type:str]
sops:
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T02:25:52Z"
    mac: ENC[AES256_GCM,data:T9HNvGedJTfvmayfCJ3bIdHWdLctAH2cG7Je28gTAr271fRsEWuHjEa8/ujQMWUGnxHro2Jn0oF8KkLTW1Etiwt4SWgGl8lmgzf/2lIz5UzW3VOqhsdTjWaiixYeVbVxjKV5JAv5afUgePArbxbf8gALOLPa2ie4dI/oeSgCVk0=,iv:Is/mahpkck/y1WAA3QGFNLTEuO1G/pEe/D3eLcEMLg0=,tag:FzEzxSIHZ1asowuyWSjlBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
