---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-database
  namespace: messaging
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: synapse-database
    template:
      engineVersion: v2
      data:
        database.yaml: |
          database:
            name: psycopg2
            args:
              user: '{{ index . "user" }}'
              password: '{{ index . "password" }}'
              host: '{{ index . "pgbouncer-host" }}'
              port: '{{ index . "port" }}'
              database: synapse
              cp_min: 5
              cp_max: 10
  dataFrom:
    - extract:
        key: postgres-pguser-synapse
