apiVersion: v1
kind: Secret
metadata:
  name: synapse-oidc
  namespace: messaging
stringData:
  oidc.yaml: ENC[AES256_GCM,data:NwWHnNjlhjmcyzuA3pWAaO7j9aYtLNvPEop99+5OfHIcZR/Lr8lh/YL+gAXPf+pw4krMiSQ5oV/mujiwkFudHoSjfq+Hr3oCt26YtUjSKSwWq2zwfs4jRhPfnSHL7KFdNsoIpDpMudIijBOMeQwmHVwWa+G6qwcK1txCwLWXEAg/Nu3XyCB959L+31HgGswkqRIWydjveAn2EUlC6MteEeqBS+JrPl1LH9fgj439HqyXlIK9IYpiDRg5xsebtipNI39vGNRsSqCyTTO6z6zQFOjvhWnsIUQJb6LcOeAYmVeAmWdlIP6ug7En14K7YEge84AmC0TLr81PDlbwfZh0o9ke4BJmCLgdr8T8KQiFkY7l2dWXMQMjFs109P8XwtCvAnZpxNKY+ZZA/fmLNzrUkFOe7q5CLz069BeH9xHs/cs4kRBdB0Ts4lNG2dMSEDo65yyc0IfNJWG969Dz155Ty5Yg10HdfRshLqFTZ6SNgCOZU6SctLN/xKciFBezlwTyEPoGf+WWdFp1rfd0Q0L9IJm4LkE3+aFKmSuRVp8JkrQmzqYTBJxPXmBYYOm39E8kn9hzn0HW5ZtzNjbi7kI1khfEcTesQIYJZuW4KDvciG0Zskj+KrYRC0S6/g3/ceE5d3b2fM6TUOkB/OeGqEx//xAuY09crPUJe98YPhS56l/w5tL6YIwfLp5WKoRn9OSp8y7s3he3/kbzfY/VugVjoXlxiNz2gj4O1fbI4N02iH9Zfcrx4uHrBYQs00jSzCSrcXqlqBnayWMQuyioNghLeQkSYdWRKlBp,iv:1pKmFMEdBxJIpQONCvPfYhMhPSpsYVtkq+Zqcsibfyw=,tag:VNObtsHIeJssW4AYdAIFNQ==,type:str]
  client_secret: ENC[AES256_GCM,data:4GPila0JusT33NUZh/LdxdI+JHrEcp707LgHoQhOs4pMhimeaS8yNcHvnCIQpUomJcIiAZFyXgEDvk9mRDGnTztYZyhW30tAgpeqdBfN7dFkxJWUt3HSOp0K3QA26sT58jDpeZK83gXKM+i4vUm6HDhFQdXSCAW1pEQCmV5EwKM=,iv:EKIy5i9JxLmpxGZEJIOLCd9F+vOAEotfoYvhzreu7H0=,tag:e+NpfUlAtk4UUhMxYRO4KQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBR2k2a3JtelRUbDU1Z0xO
        Mk5jTlNBU2lqbjRZeERZR2U5ZExWNFVZY2tnClBaRnkwSXByaG5kRW5aU0ppS2Uz
        elVQS29ZaWpudkVXdVFsOGxYOWxLWFUKLS0tIFNwU1VKRHh6djZGL0JCR0ZYK1pR
        cWRnMjIwa21rTERwaWVmOFFuTG9GdkkK+/7/pbEuL1VOP/xEh0+EmnKRVIG+tWyl
        OfBPakXzwzeT+MbPhv86MWayg5jaqNrLfvBMOAAwXpzb7/MtPNf4VA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T20:11:25Z"
  mac: ENC[AES256_GCM,data:FBFI7d4YsK/MwDR1RmqtXHp+qCXcSel1pcibkyFzmZbg2LLZ+3t5QbQnIoJr4Fqhb/lwAlwDmNmziqL52mNUIyHkBsc5V/nuoGe0XvNsq6xXwzvrEM8pXkFsHtDLWuKUo0zNDeufCjBvZOsulQcNOaEd5C8Z1YgrYpYfUfvG1TI=,iv:16jYc0/wePg9QwfuHf+Oe+CeIWt1PohflHnmKW1D/L0=,tag:1iP1iNJbsHUseOCttiiCaQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
