---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &ap shlink
  namespace: web
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        enabled: true
        containers:
          main:
            image:
              repository: shlinkio/shlink
              tag: "4.4.6"
            envFrom:
              - secretRef:
                  name: shlink-db-secret
            env:
              TIMEZONE: America/New_York
              DEFAULT_DOMAIN: &host s.${SECRET_DOMAIN}
              DISABLE_TRACKING_FROM: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
              ENABLE_PERIODIC_VISIT_LOCATE: "true"
              IS_HTTPS_ENABLED: true
              PORT: &port 80
              WEB_WORKER_NUM: 1
              GEOLITE_LICENSE_KEY: ${SECRET_GEOLINK_LICENSE_KEY}
              INITIAL_API_KEY: ${SECRET_SHLINK_API_KEY}
              SHELL_VERBOSITY: 3
              DB_DRIVER: postgres
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    service:
      main:
        controller: main
        enabled: true
        ports:
          http:
            enabled: true
            port: *port
    route:
      main:
        enabled: true
        hostnames:
          - *host
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port

    persistence:
      params:
        enabled: true
        existingClaim: shlink-config
        globalMounts:
          - path: /etc/shlink/config/params
