---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app owncloud
  namespace: cloud
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: csi-driver-cephfs
      namespace: storage
  values:
    controllers:
      owncloud:
        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          app:
            image:
              repository: owncloud/ocis
              tag: 7.1.3
              pullPolicy: IfNotPresent

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            env:
              DEMO_USERS: 'false'
              PROXY_TLS: 'false'
              OCIS_INSECURE: 'true'
              PROXY_HTTP_ADDR: '0.0.0.0:9200'
              PROXY_AUTOPROVISION_ACCOUNTS: 'true'
              PROXY_CSP_CONFIG_FILE_LOCATION: /etc/ocis/csp.yaml
              OCIS_LOG_LEVEL: 'info'
              OCIS_LOG_COLOR: 'true'
              OCIS_LOG_PRETTY: 'true'
            envFrom:
              - secretRef:
                  name: owncloud-secrets

    service:
      app:
        controller: owncloud
        ports:
          http:
            port: &port 9200

    # route:
    #   app:
    #     enabled: true
    #     hostnames:
    #       - cloud.${SECRET_DOMAIN_FBE}
    #     parentRefs:
    #       - name: external-fbe
    #         namespace: kube-system
    #         sectionName: https
    #     rules:
    #       - backendRefs:
    #           - identifier: app
    #             port: *port

    ingress:
      app:
        enabled: true
        className: "fbe"
        hosts:
          - host: &host "cloud.${SECRET_DOMAIN_FBE}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: owncloud-config
        globalMounts:
          - path: /etc/ocis
      data:
        enabled: true
        existingClaim: owncloud-data
        globalMounts:
          - path: /var/lib/ocis
