---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: home
  namespace: network
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN_FBE}"
spec:
  hostnames:
    - "home.${SECRET_DOMAIN_FBE}"
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: pgadmin
          port: 5050
