# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.100.99:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.100.99"
additionalMachineCertSans: *sans

clusterPodNets: ["10.88.0.0/16"]
clusterSvcNets: ["10.33.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos10011"
    ipAddress: "10.0.100.11"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/95d432d6bb450a67e801a6ae77c96a67e38820b62ba4159ae7e997e1695207f7
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2e:c8:01"
        vlans:
          - vlanId: 100
            addresses:
              - "10.0.100.11/22"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.0.100.1"
            vip:
              ip: "10.0.100.99"
  - hostname: "talos10012"
    ipAddress: "10.0.100.12"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/95d432d6bb450a67e801a6ae77c96a67e38820b62ba4159ae7e997e1695207f7
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2e:c8:02"
        vlans:
          - vlanId: 100
            addresses:
              - "10.0.100.12/22"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.0.100.1"
            vip:
              ip: "10.0.100.99"
  - hostname: "talos10013"
    ipAddress: "10.0.100.13"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/95d432d6bb450a67e801a6ae77c96a67e38820b62ba4159ae7e997e1695207f7
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2e:c8:03"
        vlans:
          - vlanId: 100
            addresses:
              - "10.0.100.13/22"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.0.100.1"
            vip:
              ip: "10.0.100.99"
  - hostname: "talos10014"
    ipAddress: "10.0.100.14"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/95d432d6bb450a67e801a6ae77c96a67e38820b62ba4159ae7e997e1695207f7
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2e:c8:04"
        vlans:
          - vlanId: 100
            addresses:
              - "10.0.100.14/22"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.0.100.1"
  - hostname: "talos10015"
    ipAddress: "10.0.100.15"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/95d432d6bb450a67e801a6ae77c96a67e38820b62ba4159ae7e997e1695207f7
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2e:c8:05"
        vlans:
          - vlanId: 100
            addresses:
              - "10.0.100.15/22"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.0.100.1"
  - hostname: "talos10016"
    ipAddress: "10.0.100.16"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/95d432d6bb450a67e801a6ae77c96a67e38820b62ba4159ae7e997e1695207f7
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2e:c8:06"
        vlans:
          - vlanId: 100
            addresses:
              - "10.0.100.16/22"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.0.100.1"
  - hostname: "talos10017"
    ipAddress: "10.0.100.17"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/95d432d6bb450a67e801a6ae77c96a67e38820b62ba4159ae7e997e1695207f7
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2e:c8:07"
        vlans:
          - vlanId: 100
            addresses:
              - "10.0.100.17/22"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.0.100.1"
  - hostname: "talos10018"
    ipAddress: "10.0.100.18"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/95d432d6bb450a67e801a6ae77c96a67e38820b62ba4159ae7e997e1695207f7
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2e:c8:08"
        vlans:
          - vlanId: 100
            addresses:
              - "10.0.100.18/22"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.0.100.1"
  - hostname: "talos10019"
    ipAddress: "10.0.100.19"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/d4f0e0890383069b4eb8f8ea5f59e6eee99e23aef66c9fd6ab1d1b636f654a0b
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2e:c8:09"
        vlans:
          - vlanId: 100
            addresses:
              - "10.0.100.19/22"
            mtu: 1500
            routes:
              - network: "0.0.0.0/0"
                gateway: "10.0.100.1"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

