apiVersion: v1
kind: Secret
metadata:
  name: simplex-smp-secret
  namespace: messaging
stringData:
  PASS: ENC[AES256_GCM,data:MJNHoowLe2MuJjfHZpw60afrNe9VMrtJ6psKVzZavNEj9iwviDCs5rFoOkCuchTR,iv:+5/tkhQLli2s9kTsqosJZW8zQGh8s8irkNI4jK2LdM8=,tag:BSKrkpor3peNcLQAFdfD0A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbDNmVGwyQVRFMWd5dkwv
        RDFESXJKbUc0RW15MmZwbEgxVDltSUh6bkd3Cmc4UnhCZWZWcXRvUVB2MGwrRkhj
        NTI1QTZ2aCt3dmRPL3F1MlV1ODZRSUEKLS0tIE9GSjl1dnY3UzhRcXBFRWwrMzFz
        NVo3S0tKWTJzMHFpL1hUaFlka2dtZ2sK24FtB9Ni2hn/Xub/1qSmDRo1UnSv65Cb
        Epn7Wcqq8D37hQB8RzxthTcDR2wlmszFs+j0JughJpgdsbYUDaNDMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T18:01:28Z"
  mac: ENC[AES256_GCM,data:CVkoWp0fLLhsSbM1uDhCab6jracbwc3+FUF9YfGmegWT5yyTzLDZ61z9n7haXx41lQg4gd9YqOvpEfksHjSjaGlWJxj3UcPyGEHOd0P/5MAjJ5Ag7kH/xzHYFG5Z3tDo98kzLkYsHtKZM0v0tWEC3mrqnmXR045jKHysOCD/+Pc=,iv:rnZ5rTbJwlO7aBsX4723EXO5CArTtkG0rj9HmKn/2l8=,tag:xVu02LuMNsr9Qq7haBM/Sw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
