---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soundscout-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: csi-cephfs-sc
  volumeName: soundscout-config-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: soundscout-config-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: soundscout-config
    namespace: media
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-media/soundscout/config
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: soundscout

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soundscout-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: csi-cephfs-sc
  volumeName: soundscout-data-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: soundscout-data-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: soundscout-data
    namespace: media
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-media/soundscout/data
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: soundscoutdata

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soundscout-scraper
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: csi-cephfs-sc
  volumeName: soundscout-scraper-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: soundscout-scraper-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: soundscout-scraper
    namespace: media
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-media/soundscout/scraper
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: soundscoutscraper


# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: soundscout-transcode
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 50Gi
#   storageClassName: csi-cephfs-sc
#   volumeName: soundscout-transcode-pv

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: soundscout-transcode-pv
# spec:
#   storageClassName: csi-cephfs-sc
#   claimRef:
#     name: soundscout-transcode
#     namespace: media
#   capacity:
#     storage: 50Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   csi:
#     driver: cephfs.csi.ceph.com
#     nodeStageSecretRef:
#       # node stage secret name
#       name: csi-cephfs-secret
#       # node stage secret namespace where above secret is created
#       namespace: storage
#     volumeAttributes:
#       # Required options from storageclass parameters need to be added in volumeAttributes
#       "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
#       "fsName": "k8s-cephfs"
#       "staticVolume": "true"
#       "rootPath": /volumes/csi/k8s-media/soundscout/transcode
#     # volumeHandle can be anything, need not to be same
#     # as PV name or volume name. keeping same for brevity
#     volumeHandle: plextranscode
