apiVersion: v1
kind: Secret
metadata:
    name: soundscout-secrets
    namespace: media
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:rL7fU3e8Rg1sdFlM5teIAXyTXQZSwRI4j+lwd1nOujPRGxdEeo0cdiAe30oFSbfBf1aBaAmX3F79cSGkqp9A5Q==,iv:uZDN0Fo8b3CcplAQjXhkuEb/M4PsTsLxZh3xA/w/qOg=,tag:p5bC7iNdsVeAXTZMF+6ajA==,type:str]
    LASTFM_API_KEY: ENC[AES256_GCM,data:kyjN0BugrxmZlfW6PpyBRWzLycPa9nTJmezUjaUOlZY=,iv:2fosVQ2qgK4ywMBkaJb93VN/dN1F9Fb9cbcIinKNtwE=,tag:x0TKUjTnMlhBry7zieWVAw==,type:str]
sops:
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T22:52:54Z"
    mac: ENC[AES256_GCM,data:QmjsDyBvUsGgURY+pd/6o4RHak9DIYwmYm9SG2yqREJQH40IKEojVS8jR0VqWSlgQJctpkr2rYawZjouH6NJDgExSm4mGFB1joC2eRN4hLCAMh/yI0cANfjRH0LT0cr+Mb4B4Ngxqy+IsDmciCF8YPR2M9TSa1U60iXWyS9CQPw=,iv:nI/zgtouLO0Htz5QO/0mArIHMfiOnl9gLuCNnO/vS/E=,tag:2EdsVR1NlcWPCQuR5xR/dA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
