apiVersion: v1
kind: Secret
metadata:
    name: deluge-secrets
    namespace: media
stringData:
    VPN_PASS: ENC[AES256_GCM,data:BCUepfgwjZi3eQAWJ5T22D5LzZ0hsjp2W1zCMnpZY/s=,iv:6KmqFdG7rpLiZm4Wo9YtvrLuPjgAsI2z5QSgAQQxTAk=,tag:COQ9n2OqKRcZQTGaF9YHfw==,type:str]
    VPN_USER: ENC[AES256_GCM,data:DtoowbwZph0nol24xS0+l8YAQnw=,iv:lYmZhp9nYKpjKvCTZCM+dcebcfL4H/oL7QJ+JCDmTjM=,tag:Pft7JltlodIsJVpdktr10Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T21:14:10Z"
    mac: ENC[AES256_GCM,data:FJ2O50AXPTU4GvGeLGjVj5mdr/EhphUM0pg+JrZKGnl5oI26P+uuA6t84Zsu76P/AZPS4sAOrvtQseyoKeMSTyVcCqIY5X2StylvWocpt/yqxJz51sg9kYUfvr55agIyxfZk5T+Xmqs7Xqu06nxWpfxlg/gHpymMOLPV0f6cfY4=,iv:166CTPKehCySa5TPTtIBnnRCLscC3uLMJQ9TOS1OwBY=,tag:eo0UM5L+fG6d79PxEpTTJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
