apiVersion: v1
kind: Secret
metadata:
    name: netbox-secret
    namespace: dev
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:3zessDZvtt6A2OrwWy22JTNx3EKCbedVYFa8iqtpWkSyF4Q6mkmRMXGseXhQZfAbWG1EzP9F31UNuqby2kY=,iv:fngqZoXPTHkjyOhjH4W68I9klsAqBmuQ5COEXkqDuqI=,tag:wJSYoXwKbJkhVyU/dV2F6A==,type:str]
    email-password: ENC[AES256_GCM,data:vmwO+rSO1v8ZiDlArtToPA==,iv:2Hq/R0z/cE1uAyaobrXHOyboa1CeOq867kcPVUiRJAQ=,tag:pLWdVlLViophfu4tOaDFPA==,type:str]
    username: ENC[AES256_GCM,data:zHD02FQ=,iv:k7KBCYd4zJ7K4ht01cIisO6RUfXO/IdYrBlrf22IdVk=,tag:89nq/XaQ0sO8u43/1y+oXg==,type:str]
    password: ENC[AES256_GCM,data:4cMQ8GHjs9esA+h+RA==,iv:MEXBCc2V86j7O3Fb3I9pn96gkJ3RZjrqWDVBTGb32gw=,tag:CB021tJWIOfB+qgkBzRKJA==,type:str]
    email: ENC[AES256_GCM,data:kTc+na1tTViFGhm5OC6r0v3CuNOOqX6KlMEoGXLNIh8=,iv:+3zM5iGAMLq+0UuFkrYkMHZHy9u/72yPd0jG2FxInN0=,tag:KbOZnKP957XG7bGon96ioA==,type:str]
    secret_key: ENC[AES256_GCM,data:38REZtrWE/oEVAaXgqmGb2rNNwbcPpofxke8bIK195ssAZrc5JWaGP77HQaTZzF9mN/h6TAmoeh3oKrZ8YD9fA==,iv:P1xGep8glBylgIks2B93GlziMV/LzKaBKyVppUMadJ4=,tag:s1EsJmwvu1knkiNOA6LoUw==,type:str]
sops:
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb2dDWm4raWc3MHYxVGRm
            dkhSbzVGMHF5OUhFSnVRVm9sWllaOWkvSWhnCi9OeTAxNGlyc0dDd2xmd3pySENL
            d2dPck0yelZ4VGx5Q1E1QWRBYk9rdHMKLS0tICtTVzJTSEQwQ2xSa0xSRDdsTTIw
            RjZkeEoxUmhwZGwvditNVzlvRUQ1VncKbNEf43ZE+UARbptUpniFvR8lgkgymOhr
            P4+KUx14x0d7Bh8AupvRsyXf58Wx9AX1W0c/nY2e7zPJi4LiFr7n/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-01T18:12:46Z"
    mac: ENC[AES256_GCM,data:xeNi9OH7IW4P2kypUnj4tZI7WgW1jX1RCn9KEhKVMOnhBwdK2PUL7BjxAuI+mMlPZ1MbvMJRLkC1mcBe8X6yqQSRE9IHwpMjX3M41CHMRm4argGPUry7VsEgp5xChbfi500+1m6CI3U1aWT2TDg9hHmDngbzFQ1E1pFwGoDImKw=,iv:E2UmoFa1yjwJhbPOO3SlqLxpZ0z1kRQeduR499qdWt4=,tag:3MH+WQXYdnUD5g0nTGzAtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
