---
originRequest:
  originServerName: "external.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  ## Can only use either cilium gateway or ingress-nginx, now to figure out how to do everything on either
  #- hostname: "${SECRET_DOMAIN}"
  #  service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  #- hostname: "*.${SECRET_DOMAIN}"
  #  service: https://ingress-nginx-external-controller.network.svc.cluster.local:443


  - service: http_status:404
