---
originRequest:
  originServerName: "external.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  - hostname: "${SECRET_DOMAIN_KMC}"
    service: &svck https://cilium-gateway-external-kmc.kube-system.svc.cluster.local
  - hostname: "*.${SECRET_DOMAIN_KMC}"
    service: *svck
  - hostname: "${SECRET_DOMAIN_SEPF}"
    service: &svck https://cilium-gateway-external-spf.kube-system.svc.cluster.local
  - hostname: "*.${SECRET_DOMAIN_SEPF}"
    service: *svck
  - hostname: "home.${SECRET_DOMAIN_FBE}"
    service: http://10.0.2.10
  - hostname: "whoami.${SECRET_DOMAIN_FBE}"
    service: "http://whoami.whoami.svc.cluster.local"
  - hostname: "${SECRET_DOMAIN_FBE}"
    service: &svcf https://cilium-ingress.kube-system.svc.cluster.local
  - hostname: "*.${SECRET_DOMAIN_FBE}"
    originRequest:
      noTLSVerify: true
    service: *svcf
  # - hostname: "${SECRET_DOMAIN_FBE}"
  #   service: &svcf https://cilium-gateway-external-fbe.kube-system.svc.cluster.local
  # - hostname: "*.${SECRET_DOMAIN_FBE}"
  #   service: *svcf
  ## Can only use either cilium gateway or ingress-nginx, now to figure out how to do everything on either
  #- hostname: "${SECRET_DOMAIN}"
  #  service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  #- hostname: "*.${SECRET_DOMAIN}"
  #  service: https://ingress-nginx-external-controller.network.svc.cluster.local:443


  - service: http_status:404
