---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: slskd
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: csi-driver-cephfs
      namespace: storage
    - name: csi-driver-smb
      namespace: storage
  values:
    controllers:
      slskd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/slskd/slskd
              tag: 0.22.5
            env:
              DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp/.net
              TZ: America/New_York
              SLSKD_APP_DIR: /config
              SLSKD_HTTP_PORT: &port 80
              SLSKD_NO_AUTH: true
              SLSKD_NO_HTTPS: true
              SLSKD_SLSK_LISTEN_PORT: &soulseekPort 50300
            envFrom:
              - secretRef:
                  name: slskd-secrets
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: slskd
        ports:
          http:
            port: *port
          soulseek:
            enabled: true
            port: *soulseekPort
            protocol: TCP
    # ingress:
    #   app:
    #     className: internal
    #     hosts:
    #       - host: &host "slskd.${SECRET_DOMAIN_LOCAL}"
    #         paths:
    #           - path: /
    #             service:
    #               identifier: app
    #               port: http
    route:
      main:
        enabled: true
        hostnames:
          - "slskd.${SECRET_DOMAIN_LOCAL}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port

    persistence:
      config:
        existingClaim: slskd-config
      config-file:
        type: configMap
        name: slskd-configmap
        globalMounts:
          - path: /config/slskd.yml
            subPath: slskd.yml
            readOnly: true
      tmp:
        type: emptyDir

      lcl:
        existingClaim: lcl

      downloads:
        existingClaim: lcl-downloads
        globalMounts:
          - path: /downloads
