---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      homepage:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.3.2
            env:
              TZ: ${TIMEZONE}
              LOG_LEVEL: debug
              HOMEPAGE_PROXY_DISABLE_IPV6: true
              HOMEPAGE_VAR_LIDARR_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: cluster-media-secrets
                    key: LIDARR_0_API_KEY
              HOMEPAGE_VAR_RADARR_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: cluster-media-secrets
                    key: RADARR_0_API_KEY
              HOMEPAGE_VAR_READARR_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: cluster-media-secrets
                    key: READARR_0_API_KEY
              HOMEPAGE_VAR_READARR_AUDIO_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: cluster-media-secrets
                    key: READARR_AUDIO_0_API_KEY
              HOMEPAGE_VAR_SONARR_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: cluster-media-secrets
                    key: SONARR_0_API_KEY
              HOMEPAGE_VAR_SABNZBD_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: cluster-media-secrets
                    key: SECRET_SABNZBD_API_KEY
            envFrom:
              - secretRef:
                  name: homepage-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 15m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 3000
    route:
      app:
        enabled: true
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
          - "dashboard.${SECRET_DOMAIN}"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
            readOnly: true
          - subPath: docker.yaml
            path: /app/config/docker.yaml
            readOnly: true
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
            readOnly: true
          - subPath: services.yaml
            path: /app/config/services.yaml
            readOnly: true
          - subPath: settings.yaml
            path: /app/config/settings.yaml
            readOnly: true
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
            readOnly: true
      #bookmarks:
      #  type: secret
      #  name: homepage-secret
      #  globalMounts:
      #    - subPath: bookmarks.yaml
      #      path: /app/config/bookmarks.yaml
      #      readOnly: true
