---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genrpg-dev-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-cephfs-sc
  volumeName: genrpg-dev-config-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: genrpg-dev-config-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: genrpg-dev-config
    namespace: web
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-web/genrpg/dev/config
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: genrpg-dev-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genrpg-dev-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-cephfs-sc
  volumeName: genrpg-dev-data-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: genrpg-dev-data-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: genrpg-dev-data
    namespace: web
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-web/genrpg/dev/data
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: genrpg-dev-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genrpg-dev-packages
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-cephfs-sc
  volumeName: genrpg-dev-packages-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: genrpg-dev-packages-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: genrpg-dev-packages
    namespace: web
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-web/genrpg/dev/packages
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: genrpg-dev-packages
