apiVersion: v1
kind: Secret
metadata:
    name: genrpg-dev-secret
    namespace: web
stringData:
    hello_world: ENC[AES256_GCM,data:zG4=,iv:YCJETHtSO/wAjHqz5ZaMiquvnXwGHva31o7/RTqe80c=,tag:V02AYbGUpir2NcKsF2PhyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb2dDWm4raWc3MHYxVGRm
            dkhSbzVGMHF5OUhFSnVRVm9sWllaOWkvSWhnCi9OeTAxNGlyc0dDd2xmd3pySENL
            d2dPck0yelZ4VGx5Q1E1QWRBYk9rdHMKLS0tICtTVzJTSEQwQ2xSa0xSRDdsTTIw
            RjZkeEoxUmhwZGwvditNVzlvRUQ1VncKbNEf43ZE+UARbptUpniFvR8lgkgymOhr
            P4+KUx14x0d7Bh8AupvRsyXf58Wx9AX1W0c/nY2e7zPJi4LiFr7n/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T16:56:20Z"
    mac: ENC[AES256_GCM,data:dF6r2W9kptnOGPUxJoVScewnlfuSz57iBtCNneaFshmel6uWfb2t0di+Gnyfn44GUun49++YRnrEyAslzqvA0YutIwXFUtax2Vj1Om3hWBxOi575UNTUSpGt1JWqIItvfBtysD2uC6Bl+nk6hCpjrcV+scnwxCmU1lZHpLsR3Lw=,iv:amQS3aJcaXC8rr6W1N/dNMXciR7NuOuffZwZhN45Uig=,tag:LAUNJVSrb3ozff/JpxRxUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
