apiVersion: v1
kind: Secret
metadata:
    name: genrpg-dev-secret
    namespace: web
stringData:
    SESSION_SECRET: ENC[AES256_GCM,data:sQlsWWaC6kEVooigHoRytg/ufTR4DIcHFdzgxXcpbyWHgoLkrBbDCwyeIyMGPYcsgGArR7HG1HbRvLNlndl6pg==,iv:/txdu5Ijumgq9bw1hDoutCE7K+rdRZse1BPYzPMGN6w=,tag:serVPI4mXl2WfhecNX+Gcg==,type:str]
    OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:wyR44+ORWzDM1EvAoQfQzkvNKj6at53gUvMg+OKyG9pyJQf8h2c5rHEdVr/elypl5RsbEGIVVEmegyNXf9N/HRMmlK9DgiP7UbF0ZX/APg==,iv:vVSWJ94hpcSqAyLOyQ8yXubi05zj7Y9X3PpXuy/ItfA=,tag:z1T7lz8dv6R9XCVtWyw/jg==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:SljRHQ3UHI/F8qDqy65mGgUU3RS4Y/OeIl4BKE7pz+W7HXXm6x8oFA==,iv:MioFSGNIaswvy7y1yODw3hlDH8l2JnUVKy4deq5vcJE=,tag:s8VeTeuGqsa58z5aHdlWog==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:F5ZtOUszmKgrNEidnZ4upVebG4FgrNqkbNeDeTXzBsNAf4j0lopR3HD2V1fjGKqsgP85O+MjLIr5STXZDqK57AvSTP3f8+pbwhtU3UXlS7BQ+pPFzZ8RdOWWksACTeBO0xuPvQLTT1bAx5POu3/72LwoPS73ZLS89n2FR51wUjo=,iv:djqAhaaALOxtkQgbJdvWWBTQKqk+TQ8JiNIt34ASVUU=,tag:kZJS3oIVqYf1vlpJQBYWKw==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:K8VgagwrHiwgzuOtdOqKnM+LZWk=,iv:M5BfFDCK7JUkA5rj1jV+rE9skLHlttSiBXHwSkoc1T0=,tag:HF5Ecdh8zwkw7pdU8Zzybg==,type:str]
    #ENC[AES256_GCM,data:vGXAgOHcnj9YqyDqYsA14oO7GbrDvu4xrAkAOptiaQghJWZ9q33l7U8+046Rcbl8TfY2y7fYqNXURpFrKL+bkss9iUgYJvZ0faI=,iv:q/JFigAa1Ybd88mdq+96Q0RGAh/L3feAwtqkjxDEBEI=,tag:pmDuZ1daw2whDBeQZ5v46Q==,type:comment]
    ADMIN_EMAILS: ENC[AES256_GCM,data:awnoa7MvxGzhCainYHneuWtSOfmpZPIhivJwNABqGkv5eFNmJBTQJk8SuOkkF9QdfgA=,iv:Uz60XAskCqt3Fx728ER1ymo7MX2SaBGyMzC1UrOUOn0=,tag:IeTQiRmDcyKDe9q4DGBNog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb2dDWm4raWc3MHYxVGRm
            dkhSbzVGMHF5OUhFSnVRVm9sWllaOWkvSWhnCi9OeTAxNGlyc0dDd2xmd3pySENL
            d2dPck0yelZ4VGx5Q1E1QWRBYk9rdHMKLS0tICtTVzJTSEQwQ2xSa0xSRDdsTTIw
            RjZkeEoxUmhwZGwvditNVzlvRUQ1VncKbNEf43ZE+UARbptUpniFvR8lgkgymOhr
            P4+KUx14x0d7Bh8AupvRsyXf58Wx9AX1W0c/nY2e7zPJi4LiFr7n/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T19:22:37Z"
    mac: ENC[AES256_GCM,data:S7XELWG2RUTDLzCgzRtxtRkAhtrm1YfEpOaroU8VzySyXmrqYSeDBBYzWs7xOQWZywllU7YEHbLVfP1mX6ctn0CX+dufiMgTdP0LGVS9OoPGgUYWOwbBwV3VCB9IXVZhASEOCmsfK/wBdTzfwKXNCYK8dpEXGIfslX4xSsEJVUU=,iv:lDIbiMcV8pQRtZXIuqkZ1l5Ybwh/lYVkiYEqXtdAB5E=,tag:lNoUJqLY/2vcQff8OL9zVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
