---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lidarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: csi-driver-cephfs
      namespace: storage
    - name: csi-driver-smb
      namespace: storage
  values:
    controllers:
      arr:
        pod:
          securityContext:
            runAsUser: ${PUID}
            runAsGroup: ${PGID}
            runAsNonRoot: true
            fsGroup: ${PGID}
            fsGroupChangePolicy: OnRootMismatch

        containers:
          main:
            image:
              repository: ghcr.io/home-operations/lidarr
              tag: 2.13.0.4664
            env:
              TZ: ${TIMEZONE}
              LIDARR__INSTANCE_NAME: Lidarr
              LIDARR__PORT: &port 80
              LIDARR__LOG_LEVEL: info
              LIDARR__ANALYTICS_ENABLED: "False"
              LIDARR__AUTHENTICATION_METHOD: External
              LIDARR__THEME: dark
              LIDARR__POSTGRES_HOST:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_HOST
              LIDARR__POSTGRES_MAIN_DB: "${DB_NAME}"
              LIDARR__POSTGRES_LOG_DB: "${DB_NAME}-log"
              LIDARR__POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_PASS
              LIDARR__POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: ${DB_USER}-db-secret
                    key: POSTGRES_USER
              LIDARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: cluster-media-secrets
                    key: "LIDARR_0_API_KEY"
            resources:
              requests:
                cpu: 18m
                memory: 128Mi
              limits:
                memory: 2048Mi
    service:
      main:
        controller: arr
        ports:
          http:
            port: *port
    # route:
    #   main:
    #     enabled: true
    #     hostnames:
    #       - "{{ .Release.Name }}.${SECRET_DOMAIN_LOCAL}"
    #     parentRefs:
    #       - name: internal
    #         namespace: kube-system
    #         sectionName: https

    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      lcl:
        enabled: true
        existingClaim: lcl
        globalMounts:
          - path: /lcl
      downloads:
        enabled: true
        existingClaim: lcl-downloads
        globalMounts:
          - path: /downloads
      unprocessed:
        enabled: true
        existingClaim: lcl-unprocessed
        globalMounts:
          - path: /media/unprocessed
      music:
        enabled: true
        existingClaim: lcl-music
        globalMounts:
          - path:  /media/music
      videos:
        enabled: true
        existingClaim: lcl-videos
        globalMounts:
          - path: /media/video
