---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beginnings-sepffuzzball
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      beginnings:
        pod:
          automountServiceAccountToken: false
          enableServiceLinks: false
        containers:
          main:
            image:
              repository: forge.fuzzball.enterprises/sepfy/beginnings.sepffuzzball.com
              tag: 2024.10.172022
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
    service:
      main:
        controller: beginnings
        ports:
          http:
            port: &port 80
    # ingress:
    #   main:
    #     enabled: true
    #     className: "external"
    #     annotations:
    #       external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN_SEPF}"

    #     hosts:
    #       - host: &host "beginnings.${SECRET_DOMAIN_SEPF}"
    #         paths:
    #           - path: /
    #             service:
    #               identifier: main
    #               port: http
    #     tls:
    #       - hosts:
    #           - *host
    route:
      main:
        enabled: true
        hostnames:
          - "beginnings.${SECRET_DOMAIN_SEPF}"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https-spf
        rules:
          - backendRefs:
              - identifier: main
                port: *port
