apiVersion: v1
kind: Secret
metadata:
    name: marinara-engine-secrets
    namespace: ai
stringData:
    ADMIN_SECRET: ENC[AES256_GCM,data:RvChTyYJSf7H,iv:gpTZ+xdeNORuiL+dP3NYGDtGSPXwQTCoqfkHIF8mmLo=,tag:Us7nI6KMO5GZbE1kYWMYbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T00:19:29Z"
    mac: ENC[AES256_GCM,data:OGlUo8Qc9ICtZ9Tl2dMwdGuSt7ObPCv2GIO6sAzs2szxCyloGfBlWms68SBi3J940WUy8scwEgeO+j5B06zUpDrT1HKgmho/Vi9Hz689Sw0uXzoP/zlXu6qhXIFimhHSHI+/D7sJw/RxidvLCfR45E5w1T3HrIMWzb00Xe3nDuQ=,iv:rSIAr6KIqkteZJLaEZsUXneIDEtzg63FFcU21pepmtM=,tag:aZj7vFhtwgQsSnkK+FS04w==,type:str]
    version: 3.13.2
