---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sillytavern
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: csi-driver-cephfs
      namespace: storage
  values:
    controllers:
      sillytavern:
        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          app:
            image:
              repository: ghcr.io/sillytavern/sillytavern
              tag: 1.13.0
              pullPolicy: IfNotPresent

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5


    service:
      app:
        controller: sillytavern
        ports:
          http:
            port: &port 8000
    route:
      app:
        enabled: true
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: external
            namespace: kube-system
            #sectionName: https
        rules:

          - backendRefs:
              - identifier: app
                port: *port
    # ingress:
    #   app:
    #     enabled: true
    #     className: internal
    #     hosts:
    #       - host: &host 'sillytavern.${SECRET_DOMAIN_LOCAL}'
    #         paths:
    #           - path: /
    #             service:
    #               identifier: app
    #               port: http
    #     #tls:
    #     #  - hosts:
    #     #      - *host

    persistence:
      config:
        enabled: true
        existingClaim: sillytavern-config
        globalMounts:
          - path: /home/node/app/config
      data:
        enabled: true
        existingClaim: sillytavern-data
        globalMounts:
          - path: /home/node/app/data
      plugins:
        enabled: true
        existingClaim: sillytavern-plugins
        globalMounts:
          - path: /home/node/app/plugins
