apiVersion: v1
kind: Secret
metadata:
    name: opencode-secret
    namespace: ai
stringData:
    LMSTUDIO_API_KEY: ENC[AES256_GCM,data:gKNaIDd7sR/0yk+uSg==,iv:fmzC4h+YY2At0T5XJuoe8eEPFl9io/kn+M5L3DkO1eM=,tag:Qv4t1Et+Z9DyOR/Pl5su4w==,type:str]
sops:
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T20:08:42Z"
    mac: ENC[AES256_GCM,data:Xd6cD+Ye2pUuxDKV0xpGV3WvEQdnunh1G3q+yYWlRkHl+NsbDqIwoITOTZTLLNmDZqAmHx++skTNNsx7fZeXC7uD3J7VB8TDW5znlp51f71duz6+4wqdxgvg60StxtNQJNtInsAkU8wq9E2WDS2XmXgBLBVZ/xgQrCysft/YYtE=,iv:vHQDj/39s0FjnliL3r7kM/lRM3j7fnAFMedvPK2y3Ts=,tag:sK9EDswJCDk9/Pki3r3zqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
