apiVersion: v1
kind: Secret
metadata:
  name: taskmaster-secrets
  namespace: ai
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:GQERKPghBsGIZRjqSSLAtIYOWagmbpKinAz64Uymuh6RhN7Z+sX0+Q==,iv:3QfNOQH4aKWniKcWCfmvs33zEt9zuV6fnPY6ZaCFI8E=,tag:Vs/DYxsm/4CHaEhplBFQww==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ixB8NsLUaFGTi1x9HErJjRLFbOkd2y7bN4Vtv1TjFXAlsbpq1wZSsIyfLNPeNkn2s5aGVMtVZOB8j/OCe9ce2LKiIWw3HZm1Z8G33uRROj+iBRyW4TiCYxcv6KfTTl/OCI0YhTK8KyXltCGOVaYcY9IPx7bJiZ2Kp8gJ8xsUgVQ=,iv:YunZYEsl3OQoAXApSAnZWTWiZ23hsj5BQmPkZCSwxI4=,tag:f5t/08IZnOiL5IQ20GMvVg==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:khtenLeZSPP+o2zkVhogRlAGfvFHqlXDFToiq6vrKzj1lfPqH84O9vX77/moEIRXxmI4c3gmceub6Yc2GgUjoQ==,iv:IjNVxhjGoTq/TUJWD5BHgB0AKinhIAEpqSUBbDrUoCU=,tag:34UIoQESL9OWrXiE5L0WIw==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:v+qa6YuvB3nq5zaV3VlgbfLFFHsafTM=,iv:fucimIoEarOWkJ8LGQCr2/EBZ2xIvQ6cJWqc5yQZ9cM=,tag:tgbWIgpWaedPKVrT8YrtDw==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:UZtx6vXVdN3mXOU1yzBsS3OtJEjvLPgkAJi/kzqAlyAlyBU=,iv:o8Y/GqeHfpLzLHQyhZFOc/Q7I7eGUcaPTUczY4zNM5M=,tag:zjoZamtal1tScmFMRRthxA==,type:str]
  OPENAI_MODEL: ENC[AES256_GCM,data:AanSqboePYwkRwfF9hVp4jAjI1o4rw==,iv:LzDbdC78niMPp2hqeFfohYyHQ2rfxWgHlM1H0P9cQjs=,tag:ve76/1uJJ+F8+nt3ZiN0gg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTThseWl3c0s5elNCbTNF
        dEZkWDF0RTJ0MFM1N01RdVJjUUJEcnR2dVFRCnVXMWJvQVNhY1U4SEN2S3g2Z0ZC
        NmttaXFSVWgrMm5MWnpOUFdWc1lkaW8KLS0tIDViOU9iMkpaM1k1c3BuN1dFUEF2
        NnpaeFJaNVZRSHpJQkxrYnkwRUk5OWcKw/jUFsXzjvLragTt/c7E9V+eEFEo17GW
        xUdsqn/SpS9KSDSl/1lDouf+JvsNHSnKaUNImskAUSkTrmBQ3MJm4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-16T19:41:49Z"
  mac: ENC[AES256_GCM,data:HbyZD8lUr0Itx37oAEMdWq6MeQVFYOMVcqydmi39zZUtXbUHoVTnnZ9CIiIrVvEGn64Sle+Mr2sDc+mTQ3+3JkBqEXFeOYQqffzH1DuDETSOyXiTA6FfEbzsNPO2mT8TENrQN2SGeLkHv6PFJ+BqPOjBSKcw6Jx8vkXHTd8zzio=,iv:p+3DWyOwrMfFcTsry4W3RA67Tc4wtVSPBOINZ6GuGqQ=,tag:vy5CV7RJA/nZJwyGrO/hcQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
