apiVersion: v1
kind: Secret
metadata:
  name: taskmaster-secrets
  namespace: ai
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:+hu3zMt1sRdQcUlqUkPYfYFjcFyvoduQUACiJjJIhVliIx2JhSS+rQ==,iv:qafAPokYdhCruTPxsZK1piQSNbVOXxTBC/TfzUIUm30=,tag:AHhjX96+3Q/sP5sDgvJn8g==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:U/ScWhFtMvSEUQYfHg135xwS3hMn/yFpXQ7DCoIsHtZ3FxK5hmbz9HE6YYDpiQ5vSGcKEKq6pE4Dezx0E6uokexRzH2X+96gL8moVkZZzlJBfZIPoWKoZ3PbZI2o29+dhoM2aX5vqqjgZ8MX10zlnW4O0QKARAHWQFgDv55o/pg=,iv:lkq0V0oBcuMTUZuGQPuq+7QXYax5RcurVUWAqsMJxHw=,tag:sNmvbrzuL+GDDeW4GNtRHQ==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:vu3Ymtna1KAkrU/JkjiHLXZTY7wl7KeuXW3kXLCgImCJciCjRhxmIp7nr8KFi2myrBq+fEG3KmK88EjVnMU+Qw==,iv:c+PxbddLYZMTHMcVKzKLvi+QxLAC5mY1hqAPXsO7H6E=,tag:6+2xZ4XxtDmpC1/mfTkrkg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRUppd3A0eDRDY01UcXZV
        U3pIbXJ0RlhrVEV1dThzbmx6NnZLMjI4bnlBCm9YOHJjQ25pVEdIcTZtWGdPS3hH
        ZkZrTmdUQXo0Q1hoZktkcEJnK2tWbWsKLS0tIEZKRkhSRU9xekd0TmJuQ210MExr
        Z1RFSkI0dkZaUlBiMUR1b1hnc3g3eEkKxQWBg8HUNxkvGM7HxmMJE5XvVQHOjW9j
        lwd/kQj2Fb8qqFbNW93XOFugDZOskGOwqfpRfunuRYGckPKXBl+3Vg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-15T21:53:39Z"
  mac: ENC[AES256_GCM,data:n+ce3VEzRFf/eS8yfiXEJRw6zjXYM2OlQHkKf35GsG6vZG08ovhHhsbqVHKNb2n3Y6zW2JjCk3foFtl87v775qcGXpGvAhfC16AI9b0EUFw++LoOgxAKP4PBN2qcwpV141M/ptXRoCWdlbPXJPeHQox9MCa1eqLbwxXB1KrL9XA=,iv:Y8AHxVP6EnAdiFmnAZMs+izmNPyEO8G+/UHHBe4pUS4=,tag:toJoT/pGjnB4qHWveBQUrQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
