---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blog-sepffuzzball
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      blog:
        pod:
          automountServiceAccountToken: false
          enableServiceLinks: false
          annotations:
            reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: forge.fuzzball.enterprises/sepfy/blog.sepffuzzball.com
              tag: 2024.10.172029
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
    service:
      main:
        controller: blog
        ports:
          http:
            port: &port 80
    ingress:
      main:
        enabled: true
       #annotations:
       #   - nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
       #   - nginx.ingress.kubernetes.io/ssl-passthrough: "false"
       #   - nginx.ingress.kubernetes.io/ssl-redirect: "false"
        className: "spf"
        hosts:
          - host: &host1 "www.${SECRET_DOMAIN_SEPF}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
          - host: &host2 "blog.${SECRET_DOMAIN_SEPF}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        #tls:
        #  - hosts:
        #      - *host1
        #      - *host2

    # route:
    #   main:
    #     enabled: true
    #     hostnames:
    #       - "blog.${SECRET_DOMAIN_SEPF}"
    #       - "www.${SECRET_DOMAIN_SEPF}"
    #       #- "${SECRET_DOMAIN_SEPF}"
    #     parentRefs:
    #       - name: external
    #         namespace: kube-system
    #         sectionName: https-spf
    #     rules:
    #       - backendRefs:
    #           - identifier: main
    #             port: *port
