---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blog-sepffuzzball
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      blog:
        pod:
          automountServiceAccountToken: false
          enableServiceLinks: false
          annotations:
            reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: forge.fuzzball.enterprises/sepfy/blog.sepffuzzball.com
              tag: 2024.10.172029
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
    service:
      main:
        controller: blog
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        loadBalancerIP: ${SPF_ADDR}
        ports:
          http:
            port: &port 80
    # ingress:
    #   main:
    #     enabled: true
    #     className: &class "pangolin"
    #     annotations:
    #       kubernetes.io/ingress.allow-http: "true"
    #       kubernetes.io/ingress.class: *class
    #       nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #       nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    #     hosts:
    #       - host: "${SECRET_DOMAIN_SEPF}"
    #         paths:
    #           - path: /
    #             service:
    #               identifier: main
    #               port: http
    #       - host: "${SECRET_DOMAIN_SEPFY}"
    #         paths:
    #           - path: /
    #             service:
    #               identifier: main
    #               port: http
