---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: km-weblog
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      blog:
        pod:
          automountServiceAccountToken: false
          enableServiceLinks: false
          annotations:
            reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/kylemunn/weblog
              tag: 2024.09.061335
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
    service:
      main:
        controller: blog
        ports:
          http:
            port: &port 80
    route:
      main:
        enabled: true
        hostnames:
          - "blog.${SECRET_DOMAIN_KMC}"
        parentRefs:
          - name: external-kmc
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port
