---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
components:
  - ../../components/common
#resources:
#  - ./csi-driver-nfs/ks.yaml
#  - ./csi-driver-smb/ks.yaml
#  - ./csi-driver-cephfs/ks.yaml
