---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messaging
components:
  - ../../components/common
resources:
  - ./synapse/ks.yaml
  - ./element/ks.yaml
  - ./simplex-smp/ks.yaml
  - ./simplex-xftp/ks.yaml
